/**
 * 🤖 DISCORD BOT INTEGRATION
 * Signal distribution through Discord
 */

import { Client, GatewayIntentBits, TextChannel, EmbedBuilder } from 'discord.js';
import { TradingSignal, SignalType, StrategyDefinition } from '../shared/api-schema/trading-types';

// Configure Discord client
const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
  ],
});

// Channel mapping for different subscription tiers
const CHANNEL_MAPPING: Record<string, string> = {
  free: process.env.DISCORD_CHANNEL_FREE || '',
  basic: process.env.DISCORD_CHANNEL_BASIC || '',
  pro: process.env.DISCORD_CHANNEL_PRO || '',
  enterprise: process.env.DISCORD_CHANNEL_ENTERPRISE || '',
};

// Configuration
const BOT_TOKEN = process.env.DISCORD_BOT_TOKEN || '';
const GUILD_ID = process.env.DISCORD_GUILD_ID || '';

/**
 * Initialize the Discord bot
 */
export async function initializeDiscordBot() {
  if (!BOT_TOKEN) {
    console.error('Discord bot token not provided');
    return null;
  }

  try {
    await client.login(BOT_TOKEN);
    console.log('Discord bot connected');
    
    client.on('ready', () => {
      console.log(`Logged in as ${client.user?.tag}`);
    });

    return client;
  } catch (error) {
    console.error('Failed to initialize Discord bot:', error);
    return null;
  }
}

/**
 * Format a trading signal for Discord
 */
function formatSignalEmbed(signal: TradingSignal, strategy: StrategyDefinition) {
  // Determine color based on signal type
  let color = 0x0099ff; // Default blue
  if (signal.type === SignalType.LONG) {
    color = 0x00ff00; // Green
  } else if (signal.type === SignalType.SHORT) {
    color = 0xff0000; // Red
  } else if (signal.type === SignalType.EXIT) {
    color = 0xffff00; // Yellow
  }

  // Create embed
  const embed = new EmbedBuilder()
    .setColor(color)
    .setTitle(`${signal.type} Signal - ${signal.instrumentId}`)
    .setDescription(`Generated by ${strategy.name}`)
    .addFields(
      { name: 'Confidence', value: `${(signal.confidence * 100).toFixed(2)}%`, inline: true },
      { name: 'Time', value: new Date(signal.timestamp).toLocaleString(), inline: true }
    )
    .setTimestamp()
    .setFooter({ text: 'NexQuantSite Trading Signals' });

  // Add price information if available
  if (signal.price) {
    embed.addFields({ name: 'Price', value: signal.price.toString(), inline: true });
  }

  // Add target and stop if available
  if (signal.targetPrice) {
    embed.addFields({ name: 'Target', value: signal.targetPrice.toString(), inline: true });
  }

  if (signal.stopPrice) {
    embed.addFields({ name: 'Stop', value: signal.stopPrice.toString(), inline: true });
  }

  return embed;
}

/**
 * Send a trading signal to the appropriate Discord channels
 */
export async function sendSignalToDiscord(signal: TradingSignal, strategy: StrategyDefinition) {
  if (!client || !client.isReady()) {
    console.error('Discord bot not initialized or not ready');
    return false;
  }

  try {
    const guild = client.guilds.cache.get(GUILD_ID);
    if (!guild) {
      console.error(`Guild with ID ${GUILD_ID} not found`);
      return false;
    }

    const embed = formatSignalEmbed(signal, strategy);
    let sentCount = 0;

    // Send to appropriate channels based on subscription tiers
    for (const tier of strategy.subscriptionTiers) {
      const channelId = CHANNEL_MAPPING[tier];
      if (!channelId) continue;

      const channel = guild.channels.cache.get(channelId) as TextChannel | undefined;
      if (channel && channel.isTextBased()) {
        await channel.send({ embeds: [embed] });
        sentCount++;
      }
    }

    console.log(`Signal sent to ${sentCount} Discord channels`);
    return sentCount > 0;
  } catch (error) {
    console.error('Error sending signal to Discord:', error);
    return false;
  }
}

/**
 * Send a performance update to Discord
 */
export async function sendPerformanceUpdate(strategyId: string, period: string, winRate: number, profitFactor: number) {
  if (!client || !client.isReady()) {
    console.error('Discord bot not initialized or not ready');
    return false;
  }

  try {
    const guild = client.guilds.cache.get(GUILD_ID);
    if (!guild) {
      console.error(`Guild with ID ${GUILD_ID} not found`);
      return false;
    }

    // Create performance embed
    const embed = new EmbedBuilder()
      .setColor(0x0099ff)
      .setTitle(`Performance Update - ${strategyId}`)
      .setDescription(`Performance metrics for the ${period} period`)
      .addFields(
        { name: 'Win Rate', value: `${(winRate * 100).toFixed(2)}%`, inline: true },
        { name: 'Profit Factor', value: profitFactor.toFixed(2), inline: true }
      )
      .setTimestamp()
      .setFooter({ text: 'NexQuantSite Performance Metrics' });

    // Send to the general updates channel (could be customized per tier)
    const channelId = process.env.DISCORD_CHANNEL_UPDATES || '';
    if (!channelId) {
      console.error('Updates channel not configured');
      return false;
    }

    const channel = guild.channels.cache.get(channelId) as TextChannel | undefined;
    if (channel && channel.isTextBased()) {
      await channel.send({ embeds: [embed] });
      console.log('Performance update sent to Discord');
      return true;
    }

    return false;
  } catch (error) {
    console.error('Error sending performance update to Discord:', error);
    return false;
  }
}

// Export default client
export default client;
