#!/usr/bin/env python3
"""
STANDARDIZED SIGNAL FORMAT
Defines a consistent format for trading signals generated by ML models
"""

import json
import uuid
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Any, Union, TypedDict


class SignalType(str, Enum):
    """Types of trading signals"""
    ENTRY = "entry"
    EXIT = "exit"
    STOP_LOSS = "stop_loss"
    TAKE_PROFIT = "take_profit"
    RISK_ADJUSTMENT = "risk_adjustment"
    POSITION_SIZE = "position_size"
    MARKET_REGIME = "market_regime"
    CORRELATION = "correlation"
    VOLATILITY_ALERT = "volatility_alert"
    CUSTOM = "custom"


class SignalDirection(str, Enum):
    """Direction of trading signals"""
    LONG = "long"
    SHORT = "short"
    NEUTRAL = "neutral"
    CLOSE = "close"


class SignalTimeframe(str, Enum):
    """Standard timeframes for signals"""
    M1 = "1m"
    M5 = "5m"
    M15 = "15m"
    M30 = "30m"
    H1 = "1h"
    H4 = "4h"
    D1 = "1d"
    W1 = "1w"
    MN1 = "1M"


class SignalStrength(str, Enum):
    """Signal strength classifications"""
    VERY_WEAK = "very_weak"
    WEAK = "weak"
    MODERATE = "moderate"
    STRONG = "strong"
    VERY_STRONG = "very_strong"


class SignalSource(str, Enum):
    """Source of the signal"""
    MODEL = "model"
    RULE = "rule"
    ENSEMBLE = "ensemble"
    HUMAN = "human"
    HYBRID = "hybrid"


class SignalStatus(str, Enum):
    """Status of the signal"""
    PENDING = "pending"
    ACTIVE = "active"
    EXECUTED = "executed"
    EXPIRED = "expired"
    CANCELED = "canceled"
    PARTIALLY_FILLED = "partially_filled"
    FILLED = "filled"


class SignalConfidenceMetrics(TypedDict, total=False):
    """Confidence metrics for a signal"""
    probability: float  # Probability score (0-1)
    z_score: Optional[float]  # Z-score of the prediction
    percentile: Optional[float]  # Percentile rank
    sharpe_ratio: Optional[float]  # Expected Sharpe ratio
    win_rate: Optional[float]  # Historical win rate for similar signals
    profit_factor: Optional[float]  # Historical profit factor
    variance: Optional[float]  # Variance/uncertainty of the prediction
    model_agreement: Optional[float]  # Agreement between models (0-1)
    confidence_interval: Optional[List[float]]  # Confidence interval [lower, upper]


class PriceLevel(TypedDict, total=False):
    """Price level with optional metadata"""
    price: float
    type: str  # e.g., "support", "resistance", "pivot", etc.
    strength: Optional[float]  # Strength score (0-1)
    description: Optional[str]
    timeframe: Optional[str]  # Timeframe this level was identified on


class Signal:
    """
    Standardized trading signal format
    
    This class represents a trading signal with all necessary metadata
    for proper interpretation and execution.
    """
    
    def __init__(
        self,
        # Required fields
        instrument_id: str,
        signal_type: Union[SignalType, str],
        timestamp: Optional[datetime] = None,
        
        # Signal details
        direction: Optional[Union[SignalDirection, str]] = None,
        timeframe: Optional[Union[SignalTimeframe, str]] = None,
        expiration: Optional[datetime] = None,
        strength: Optional[Union[SignalStrength, str]] = None,
        
        # Identification and tracking
        signal_id: Optional[str] = None,
        strategy_id: Optional[str] = None,
        model_id: Optional[str] = None,
        model_version: Optional[str] = None,
        source: Optional[Union[SignalSource, str]] = SignalSource.MODEL,
        
        # Price information
        entry_price: Optional[float] = None,
        current_price: Optional[float] = None,
        stop_loss: Optional[float] = None,
        take_profit: Optional[float] = None,
        price_levels: Optional[List[PriceLevel]] = None,
        
        # Risk and position sizing
        risk_reward_ratio: Optional[float] = None,
        position_size: Optional[float] = None,
        risk_per_trade: Optional[float] = None,
        max_risk: Optional[float] = None,
        
        # Performance and quality metrics
        confidence: Optional[float] = None,
        confidence_metrics: Optional[SignalConfidenceMetrics] = None,
        expected_return: Optional[float] = None,
        expected_drawdown: Optional[float] = None,
        
        # Status and execution
        status: Optional[Union[SignalStatus, str]] = SignalStatus.PENDING,
        execution_time: Optional[datetime] = None,
        execution_price: Optional[float] = None,
        
        # Additional data
        metadata: Optional[Dict[str, Any]] = None,
        features: Optional[Dict[str, Any]] = None,
        tags: Optional[List[str]] = None,
        related_signals: Optional[List[str]] = None,
        context: Optional[Dict[str, Any]] = None
    ):
        # Generate signal_id if not provided
        self.signal_id = signal_id or str(uuid.uuid4())
        
        # Required fields
        self.instrument_id = instrument_id
        self.signal_type = signal_type if isinstance(signal_type, SignalType) else SignalType(signal_type)
        self.timestamp = timestamp or datetime.now()
        
        # Signal details
        self.direction = direction if isinstance(direction, SignalDirection) else (
            SignalDirection(direction) if direction else None
        )
        self.timeframe = timeframe if isinstance(timeframe, SignalTimeframe) else (
            SignalTimeframe(timeframe) if timeframe else None
        )
        self.expiration = expiration
        self.strength = strength if isinstance(strength, SignalStrength) else (
            SignalStrength(strength) if strength else None
        )
        
        # Identification and tracking
        self.strategy_id = strategy_id
        self.model_id = model_id
        self.model_version = model_version
        self.source = source if isinstance(source, SignalSource) else SignalSource(source)
        
        # Price information
        self.entry_price = entry_price
        self.current_price = current_price
        self.stop_loss = stop_loss
        self.take_profit = take_profit
        self.price_levels = price_levels or []
        
        # Risk and position sizing
        self.risk_reward_ratio = risk_reward_ratio
        self.position_size = position_size
        self.risk_per_trade = risk_per_trade
        self.max_risk = max_risk
        
        # Performance and quality metrics
        self.confidence = confidence
        self.confidence_metrics = confidence_metrics or {}
        self.expected_return = expected_return
        self.expected_drawdown = expected_drawdown
        
        # Status and execution
        self.status = status if isinstance(status, SignalStatus) else SignalStatus(status)
        self.execution_time = execution_time
        self.execution_price = execution_price
        
        # Additional data
        self.metadata = metadata or {}
        self.features = features or {}
        self.tags = tags or []
        self.related_signals = related_signals or []
        self.context = context or {}
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary format for serialization"""
        result = {
            "signal_id": self.signal_id,
            "instrument_id": self.instrument_id,
            "signal_type": self.signal_type.value,
            "timestamp": self.timestamp.isoformat(),
        }
        
        # Add optional fields if they exist
        if self.direction:
            result["direction"] = self.direction.value
        
        if self.timeframe:
            result["timeframe"] = self.timeframe.value
        
        if self.expiration:
            result["expiration"] = self.expiration.isoformat()
        
        if self.strength:
            result["strength"] = self.strength.value
        
        if self.strategy_id:
            result["strategy_id"] = self.strategy_id
        
        if self.model_id:
            result["model_id"] = self.model_id
        
        if self.model_version:
            result["model_version"] = self.model_version
        
        if self.source:
            result["source"] = self.source.value
        
        if self.entry_price is not None:
            result["entry_price"] = self.entry_price
        
        if self.current_price is not None:
            result["current_price"] = self.current_price
        
        if self.stop_loss is not None:
            result["stop_loss"] = self.stop_loss
        
        if self.take_profit is not None:
            result["take_profit"] = self.take_profit
        
        if self.price_levels:
            result["price_levels"] = self.price_levels
        
        if self.risk_reward_ratio is not None:
            result["risk_reward_ratio"] = self.risk_reward_ratio
        
        if self.position_size is not None:
            result["position_size"] = self.position_size
        
        if self.risk_per_trade is not None:
            result["risk_per_trade"] = self.risk_per_trade
        
        if self.max_risk is not None:
            result["max_risk"] = self.max_risk
        
        if self.confidence is not None:
            result["confidence"] = self.confidence
        
        if self.confidence_metrics:
            result["confidence_metrics"] = self.confidence_metrics
        
        if self.expected_return is not None:
            result["expected_return"] = self.expected_return
        
        if self.expected_drawdown is not None:
            result["expected_drawdown"] = self.expected_drawdown
        
        if self.status:
            result["status"] = self.status.value
        
        if self.execution_time:
            result["execution_time"] = self.execution_time.isoformat()
        
        if self.execution_price is not None:
            result["execution_price"] = self.execution_price
        
        if self.metadata:
            result["metadata"] = self.metadata
        
        if self.features:
            result["features"] = self.features
        
        if self.tags:
            result["tags"] = self.tags
        
        if self.related_signals:
            result["related_signals"] = self.related_signals
        
        if self.context:
            result["context"] = self.context
        
        return result
    
    def to_json(self, pretty: bool = False) -> str:
        """Convert signal to JSON string"""
        indent = 2 if pretty else None
        return json.dumps(self.to_dict(), indent=indent)
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Signal":
        """Create signal from dictionary data"""
        # Convert ISO format strings to datetime objects
        if "timestamp" in data and isinstance(data["timestamp"], str):
            data["timestamp"] = datetime.fromisoformat(data["timestamp"])
        
        if "expiration" in data and isinstance(data["expiration"], str):
            data["expiration"] = datetime.fromisoformat(data["expiration"])
        
        if "execution_time" in data and isinstance(data["execution_time"], str):
            data["execution_time"] = datetime.fromisoformat(data["execution_time"])
        
        return cls(**data)
    
    @classmethod
    def from_json(cls, json_str: str) -> "Signal":
        """Create signal from JSON string"""
        data = json.loads(json_str)
        return cls.from_dict(data)
    
    def validate(self) -> List[str]:
        """Validate signal data and return list of validation errors"""
        errors = []
        
        # Check required fields
        if not self.instrument_id:
            errors.append("instrument_id is required")
        
        # Validate signal type
        try:
            if not isinstance(self.signal_type, SignalType):
                SignalType(self.signal_type)
        except ValueError:
            errors.append(f"Invalid signal_type: {self.signal_type}")
        
        # Validate direction if provided
        if self.direction and not isinstance(self.direction, SignalDirection):
            try:
                SignalDirection(self.direction)
            except ValueError:
                errors.append(f"Invalid direction: {self.direction}")
        
        # Validate timeframe if provided
        if self.timeframe and not isinstance(self.timeframe, SignalTimeframe):
            try:
                SignalTimeframe(self.timeframe)
            except ValueError:
                errors.append(f"Invalid timeframe: {self.timeframe}")
        
        # Validate numerical fields
        if self.confidence is not None and (self.confidence < 0 or self.confidence > 1):
            errors.append(f"Confidence must be between 0 and 1, got {self.confidence}")
        
        if self.risk_reward_ratio is not None and self.risk_reward_ratio <= 0:
            errors.append(f"Risk-reward ratio must be positive, got {self.risk_reward_ratio}")
        
        # Validate price consistency
        if self.direction == SignalDirection.LONG:
            if self.stop_loss is not None and self.entry_price is not None and self.stop_loss >= self.entry_price:
                errors.append(f"For LONG signals, stop_loss ({self.stop_loss}) must be below entry_price ({self.entry_price})")
            
            if self.take_profit is not None and self.entry_price is not None and self.take_profit <= self.entry_price:
                errors.append(f"For LONG signals, take_profit ({self.take_profit}) must be above entry_price ({self.entry_price})")
        
        elif self.direction == SignalDirection.SHORT:
            if self.stop_loss is not None and self.entry_price is not None and self.stop_loss <= self.entry_price:
                errors.append(f"For SHORT signals, stop_loss ({self.stop_loss}) must be above entry_price ({self.entry_price})")
            
            if self.take_profit is not None and self.entry_price is not None and self.take_profit >= self.entry_price:
                errors.append(f"For SHORT signals, take_profit ({self.take_profit}) must be below entry_price ({self.entry_price})")
        
        return errors
    
    def is_valid(self) -> bool:
        """Check if signal is valid"""
        return len(self.validate()) == 0
    
    def __str__(self) -> str:
        """String representation of signal"""
        direction_str = f" {self.direction.value}" if self.direction else ""
        return f"Signal({self.signal_type.value}{direction_str} for {self.instrument_id})"
    
    def __repr__(self) -> str:
        """Detailed representation of signal"""
        return f"Signal(id={self.signal_id}, type={self.signal_type.value}, instrument={self.instrument_id})"


class SignalBatch:
    """A batch of signals with common metadata"""
    
    def __init__(
        self,
        signals: List[Signal],
        batch_id: Optional[str] = None,
        timestamp: Optional[datetime] = None,
        strategy_id: Optional[str] = None,
        model_id: Optional[str] = None,
        model_version: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None
    ):
        self.signals = signals
        self.batch_id = batch_id or str(uuid.uuid4())
        self.timestamp = timestamp or datetime.now()
        self.strategy_id = strategy_id
        self.model_id = model_id
        self.model_version = model_version
        self.metadata = metadata or {}
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert batch to dictionary format for serialization"""
        return {
            "batch_id": self.batch_id,
            "timestamp": self.timestamp.isoformat(),
            "strategy_id": self.strategy_id,
            "model_id": self.model_id,
            "model_version": self.model_version,
            "metadata": self.metadata,
            "signals": [signal.to_dict() for signal in self.signals],
            "count": len(self.signals)
        }
    
    def to_json(self, pretty: bool = False) -> str:
        """Convert batch to JSON string"""
        indent = 2 if pretty else None
        return json.dumps(self.to_dict(), indent=indent)
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SignalBatch":
        """Create batch from dictionary data"""
        # Extract and convert signals
        signals_data = data.pop("signals", [])
        signals = [Signal.from_dict(signal_data) for signal_data in signals_data]
        
        # Convert timestamp
        if "timestamp" in data and isinstance(data["timestamp"], str):
            data["timestamp"] = datetime.fromisoformat(data["timestamp"])
        
        # Remove count if present
        data.pop("count", None)
        
        return cls(signals=signals, **data)
    
    @classmethod
    def from_json(cls, json_str: str) -> "SignalBatch":
        """Create batch from JSON string"""
        data = json.loads(json_str)
        return cls.from_dict(data)
    
    def validate(self) -> List[str]:
        """Validate all signals in the batch and return list of validation errors"""
        errors = []
        
        for i, signal in enumerate(self.signals):
            signal_errors = signal.validate()
            if signal_errors:
                for error in signal_errors:
                    errors.append(f"Signal {i} ({signal.signal_id}): {error}")
        
        return errors
    
    def is_valid(self) -> bool:
        """Check if all signals in the batch are valid"""
        return len(self.validate()) == 0
    
    def __len__(self) -> int:
        """Number of signals in the batch"""
        return len(self.signals)
    
    def __getitem__(self, index) -> Signal:
        """Get signal at specific index"""
        return self.signals[index]
    
    def __iter__(self):
        """Iterate over signals"""
        return iter(self.signals)
    
    def __str__(self) -> str:
        """String representation of batch"""
        return f"SignalBatch({len(self.signals)} signals, id={self.batch_id})"


# Example usage
if __name__ == "__main__":
    # Create a simple signal
    signal = Signal(
        instrument_id="BTCUSD",
        signal_type=SignalType.ENTRY,
        direction=SignalDirection.LONG,
        timeframe=SignalTimeframe.H1,
        entry_price=50000.0,
        stop_loss=49000.0,
        take_profit=52000.0,
        confidence=0.85,
        confidence_metrics={
            "probability": 0.85,
            "model_agreement": 0.9,
            "win_rate": 0.65
        },
        strategy_id="trend_following_v1",
        model_id="btc_prediction_model",
        model_version="v1.2.3",
        tags=["crypto", "bitcoin", "trend"]
    )
    
    # Convert to JSON and back
    json_str = signal.to_json(pretty=True)
    print(json_str)
    
    # Validate the signal
    validation_errors = signal.validate()
    if validation_errors:
        print("\nValidation errors:")
        for error in validation_errors:
            print(f"- {error}")
    else:
        print("\nSignal is valid")
    
    # Create a batch of signals
    batch = SignalBatch(
        signals=[signal],
        strategy_id="trend_following_v1",
        model_id="btc_prediction_model",
        model_version="v1.2.3",
        metadata={"source": "backtest", "period": "2023-01-01 to 2023-06-30"}
    )
    
    batch_json = batch.to_json(pretty=True)
    print(f"\nBatch JSON: {batch_json}")
