export type Ingredient = {
  id: string
  title: string
  desc: string
  category: string
  complexity: 1 | 2 | 3
  tags: string[]
  icon: "BarChart" | "BrainCircuit" | "Bot" | "ShieldCheck" | "Rocket" | "Beaker"
}

export type Strategy = {
  id: string
  title: string
  desc: string
  type: string
  category: string
  difficulty: 1 | 2 | 3 | 4 | 5
  components: string[]
  metrics: { label: string; value: string }[]
  implementation: { title: string; desc: string }[]
  risks: string
  featured?: boolean
}

export const ingredients: Ingredient[] = [
  // DATA CATEGORY - Raw data sources and feeds (35 ingredients)
  {
    id: "ohlcv",
    title: "OHLCV Data",
    desc: "The foundation of technical analysis. Open, High, Low, Close, and Volume data forms the basis for most trading strategies and indicators.",
    category: "data",
    complexity: 1,
    tags: ["Price Action", "Historical Data", "Candlesticks"],
    icon: "BarChart",
  },
  {
    id: "orderbook",
    title: "Order Book Data",
    desc: "Real-time Level 2/3 market depth showing all buy and sell orders. Essential for market making and understanding true supply/demand dynamics.",
    category: "data",
    complexity: 2,
    tags: ["Market Depth", "Liquidity", "Microstructure"],
    icon: "BarChart",
  },
  {
    id: "tickdata",
    title: "Tick Data",
    desc: "Every individual trade and quote update. The most granular data available, used by HFT firms for microsecond-level analysis.",
    category: "data",
    complexity: 3,
    tags: ["High Frequency", "Time & Sales", "Raw Feed"],
    icon: "BarChart",
  },
  {
    id: "alternative",
    title: "Alternative Data",
    desc: "Non-traditional data sources like satellite imagery, web scraping, credit card transactions, and social media sentiment for unique alpha generation.",
    category: "data",
    complexity: 3,
    tags: ["Satellite", "Web Data", "Sentiment"],
    icon: "BarChart",
  },
  {
    id: "options-chain",
    title: "Options Chain Data",
    desc: "Complete options chain with Greeks, implied volatility, and open interest. Critical for volatility trading and hedging strategies.",
    category: "data",
    complexity: 2,
    tags: ["Greeks", "IV Surface", "Skew"],
    icon: "BarChart",
  },
  {
    id: "fundamental",
    title: "Fundamental Data",
    desc: "Financial statements, earnings reports, economic indicators, and company metrics for value-based strategies and macro trading.",
    category: "data",
    complexity: 1,
    tags: ["Financials", "Ratios", "Earnings"],
    icon: "BarChart",
  },
  {
    id: "economic-indicators",
    title: "Economic Indicators",
    desc: "GDP, inflation, employment data, central bank rates, and other macroeconomic indicators that drive market movements.",
    category: "data",
    complexity: 2,
    tags: ["Macro", "GDP", "Inflation", "Fed Rates"],
    icon: "BarChart",
  },
  {
    id: "earnings-data",
    title: "Earnings Data",
    desc: "Quarterly earnings reports, guidance, analyst estimates, and earnings surprises for fundamental analysis and event-driven strategies.",
    category: "data",
    complexity: 1,
    tags: ["EPS", "Revenue", "Guidance", "Surprises"],
    icon: "BarChart",
  },
  {
    id: "insider-trading",
    title: "Insider Trading Data",
    desc: "Corporate insider buy/sell transactions, Form 4 filings, and executive trading patterns for sentiment analysis.",
    category: "data",
    complexity: 2,
    tags: ["Form 4", "Executive Trading", "Insider Sentiment"],
    icon: "BarChart",
  },
  {
    id: "short-interest",
    title: "Short Interest Data",
    desc: "Short interest ratios, days to cover, and borrowing costs for identifying squeeze opportunities and sentiment extremes.",
    category: "data",
    complexity: 2,
    tags: ["Short Squeeze", "Borrow Rates", "Float"],
    icon: "BarChart",
  },
  {
    id: "institutional-flows",
    title: "Institutional Flow Data",
    desc: "13F filings, institutional ownership changes, and smart money flows for following sophisticated investors.",
    category: "data",
    complexity: 2,
    tags: ["13F", "Smart Money", "Institutional"],
    icon: "BarChart",
  },
  {
    id: "etf-flows",
    title: "ETF Flow Data",
    desc: "Daily ETF creation/redemption data, sector rotation flows, and passive investment trends for market structure analysis.",
    category: "data",
    complexity: 2,
    tags: ["Creation Units", "Sector Rotation", "Passive Flows"],
    icon: "BarChart",
  },
  {
    id: "futures-cot",
    title: "Futures COT Data",
    desc: "Commitment of Traders reports showing positioning of commercials, large specs, and retail traders in futures markets.",
    category: "data",
    complexity: 2,
    tags: ["COT", "Positioning", "Commercials", "Specs"],
    icon: "BarChart",
  },
  {
    id: "crypto-onchain",
    title: "On-Chain Data",
    desc: "Blockchain transaction data, wallet movements, exchange flows, and network metrics for cryptocurrency analysis.",
    category: "data",
    complexity: 3,
    tags: ["Blockchain", "Whale Movements", "Exchange Flows"],
    icon: "BarChart",
  },
  {
    id: "defi-metrics",
    title: "DeFi Metrics",
    desc: "Total Value Locked (TVL), yield farming rates, liquidity pool data, and protocol metrics for DeFi strategies.",
    category: "data",
    complexity: 3,
    tags: ["TVL", "Yield Farming", "Liquidity Pools"],
    icon: "BarChart",
  },
  {
    id: "social-sentiment",
    title: "Social Media Data",
    desc: "Twitter sentiment, Reddit discussions, Discord activity, and social media mentions for retail sentiment analysis.",
    category: "data",
    complexity: 2,
    tags: ["Twitter", "Reddit", "Social Sentiment"],
    icon: "BarChart",
  },
  {
    id: "news-data",
    title: "News & Media Data",
    desc: "Real-time news feeds, press releases, analyst reports, and media sentiment for event-driven strategies.",
    category: "data",
    complexity: 2,
    tags: ["News Feed", "Press Releases", "Media Sentiment"],
    icon: "BarChart",
  },
  {
    id: "satellite-data",
    title: "Satellite Imagery",
    desc: "Agricultural crop monitoring, oil storage levels, retail foot traffic, and economic activity from satellite imagery.",
    category: "data",
    complexity: 3,
    tags: ["Agriculture", "Oil Storage", "Foot Traffic"],
    icon: "BarChart",
  },
  {
    id: "weather-data",
    title: "Weather Data",
    desc: "Temperature, precipitation, and weather patterns for agricultural commodities and energy trading strategies.",
    category: "data",
    complexity: 2,
    tags: ["Agriculture", "Energy", "Climate"],
    icon: "BarChart",
  },
  {
    id: "credit-data",
    title: "Credit Market Data",
    desc: "Corporate bond spreads, credit default swaps, and credit ratings for fixed income and credit strategies.",
    category: "data",
    complexity: 2,
    tags: ["Credit Spreads", "CDS", "Bond Yields"],
    icon: "BarChart",
  },
  {
    id: "fx-data",
    title: "Foreign Exchange Data",
    desc: "Currency pairs, central bank interventions, carry trade metrics, and FX volatility for currency strategies.",
    category: "data",
    complexity: 2,
    tags: ["Currency Pairs", "Carry Trade", "FX Vol"],
    icon: "BarChart",
  },
  {
    id: "commodity-data",
    title: "Commodity Data",
    desc: "Futures prices, inventory levels, production data, and supply/demand fundamentals for commodity trading.",
    category: "data",
    complexity: 2,
    tags: ["Futures", "Inventory", "Supply/Demand"],
    icon: "BarChart",
  },
  {
    id: "yield-curve",
    title: "Yield Curve Data",
    desc: "Government bond yields across maturities, yield curve shapes, and term structure analysis for fixed income strategies.",
    category: "data",
    complexity: 2,
    tags: ["Term Structure", "Curve Steepening", "Duration"],
    icon: "BarChart",
  },
  {
    id: "volatility-surface",
    title: "Volatility Surface Data",
    desc: "Implied volatility across strikes and expirations, volatility skew, and term structure for options strategies.",
    category: "data",
    complexity: 3,
    tags: ["IV Surface", "Volatility Skew", "Term Structure"],
    icon: "BarChart",
  },
  {
    id: "cross-asset-correlations",
    title: "Cross-Asset Correlations",
    desc: "Real-time correlation matrices across asset classes, correlation breakdowns, and regime-dependent correlations.",
    category: "data",
    complexity: 2,
    tags: ["Correlation Matrix", "Cross-Asset", "Regime Dependent"],
    icon: "BarChart",
  },
  {
    id: "market-structure",
    title: "Market Structure Data",
    desc: "Exchange market share, dark pool activity, internalization rates, and market fragmentation metrics.",
    category: "data",
    complexity: 3,
    tags: ["Market Share", "Dark Pools", "Fragmentation"],
    icon: "BarChart",
  },
  {
    id: "regulatory-filings",
    title: "Regulatory Filings",
    desc: "SEC filings, proxy statements, merger documents, and regulatory announcements for event-driven strategies.",
    category: "data",
    complexity: 2,
    tags: ["SEC Filings", "Proxy Statements", "M&A"],
    icon: "BarChart",
  },
  {
    id: "patent-data",
    title: "Patent & IP Data",
    desc: "Patent filings, intellectual property portfolios, and innovation metrics for technology sector analysis.",
    category: "data",
    complexity: 2,
    tags: ["Patents", "IP Portfolio", "Innovation"],
    icon: "BarChart",
  },
  {
    id: "supply-chain",
    title: "Supply Chain Data",
    desc: "Shipping rates, port congestion, supply chain disruptions, and logistics data for sector rotation strategies.",
    category: "data",
    complexity: 2,
    tags: ["Shipping Rates", "Port Data", "Supply Chain"],
    icon: "BarChart",
  },
  {
    id: "energy-data",
    title: "Energy Market Data",
    desc: "Oil inventories, natural gas storage, renewable energy production, and energy consumption patterns.",
    category: "data",
    complexity: 2,
    tags: ["Oil Inventories", "Gas Storage", "Renewables"],
    icon: "BarChart",
  },
  {
    id: "real-estate",
    title: "Real Estate Data",
    desc: "Property prices, REIT performance, construction permits, and real estate investment flows for property strategies.",
    category: "data",
    complexity: 2,
    tags: ["Property Prices", "REITs", "Construction"],
    icon: "BarChart",
  },
  {
    id: "demographic-data",
    title: "Demographic Data",
    desc: "Population trends, age distributions, migration patterns, and demographic shifts for long-term thematic investing.",
    category: "data",
    complexity: 2,
    tags: ["Population", "Demographics", "Migration"],
    icon: "BarChart",
  },
  {
    id: "geopolitical-risk",
    title: "Geopolitical Risk Data",
    desc: "Political stability indices, election probabilities, trade war metrics, and geopolitical event data.",
    category: "data",
    complexity: 3,
    tags: ["Political Risk", "Elections", "Trade Wars"],
    icon: "BarChart",
  },
  {
    id: "central-bank-data",
    title: "Central Bank Data",
    desc: "Central bank balance sheets, policy meeting minutes, forward guidance, and monetary policy indicators.",
    category: "data",
    complexity: 2,
    tags: ["Balance Sheets", "Policy Minutes", "Forward Guidance"],
    icon: "BarChart",
  },
  {
    id: "high-frequency-indicators",
    title: "High-Frequency Economic Indicators",
    desc: "Daily economic nowcasting, Google trends, electricity consumption, and real-time economic activity measures.",
    category: "data",
    complexity: 3,
    tags: ["Nowcasting", "Google Trends", "Real-time"],
    icon: "BarChart",
  },

  // ANALYSIS CATEGORY - Technical analysis, statistical models, mathematical techniques (40 ingredients)
  {
    id: "technical",
    title: "Technical Indicators",
    desc: "Mathematical calculations on price and volume data. From simple moving averages to complex oscillators like RSI, MACD, and Bollinger Bands.",
    category: "analysis",
    complexity: 1,
    tags: ["Moving Averages", "Oscillators", "Momentum"],
    icon: "Beaker",
  },
  {
    id: "statistical",
    title: "Statistical Models",
    desc: "Advanced mathematical models including ARIMA, GARCH for volatility, cointegration tests, and regime-switching models for market analysis.",
    category: "analysis",
    complexity: 3,
    tags: ["Time Series", "Cointegration", "GARCH"],
    icon: "Beaker",
  },
  {
    id: "microstructure",
    title: "Market Microstructure",
    desc: "Study of order flow, market impact, bid-ask spreads, and price discovery mechanisms. Critical for execution optimization.",
    category: "analysis",
    complexity: 3,
    tags: ["Order Flow", "Market Impact", "Spreads"],
    icon: "Beaker",
  },
  {
    id: "factor",
    title: "Factor Models",
    desc: "Decompose returns into systematic factors like value, momentum, quality, and volatility. Foundation of smart beta and risk premia strategies.",
    category: "analysis",
    complexity: 2,
    tags: ["Fama-French", "Risk Factors", "Alpha"],
    icon: "Beaker",
  },
  {
    id: "wavelet",
    title: "Wavelet Analysis",
    desc: "Multi-resolution time-frequency analysis for detecting patterns at different time scales. Superior to Fourier for non-stationary financial data.",
    category: "analysis",
    complexity: 3,
    tags: ["Signal Processing", "Multi-Scale", "Denoising"],
    icon: "Beaker",
  },
  {
    id: "entropy",
    title: "Market Entropy",
    desc: "Information theory applied to markets. Measure market efficiency, predictability, and regime changes using Shannon entropy and mutual information.",
    category: "analysis",
    complexity: 3,
    tags: ["Information Theory", "Efficiency", "Complexity"],
    icon: "Beaker",
  },
  {
    id: "fractal-analysis",
    title: "Fractal Analysis",
    desc: "Study of self-similar patterns in market data using Hurst exponent, fractal dimension, and multifractal analysis for trend persistence.",
    category: "analysis",
    complexity: 3,
    tags: ["Hurst Exponent", "Self-Similarity", "Trend Persistence"],
    icon: "Beaker",
  },
  {
    id: "correlation-analysis",
    title: "Correlation Analysis",
    desc: "Dynamic correlation matrices, rolling correlations, and correlation breakdowns during market stress for portfolio construction.",
    category: "analysis",
    complexity: 2,
    tags: ["Dynamic Correlation", "Correlation Matrix", "Market Stress"],
    icon: "Beaker",
  },
  {
    id: "volatility-modeling",
    title: "Volatility Modeling",
    desc: "GARCH, EGARCH, and stochastic volatility models for forecasting volatility and volatility clustering analysis.",
    category: "analysis",
    complexity: 3,
    tags: ["GARCH", "Stochastic Vol", "Vol Clustering"],
    icon: "Beaker",
  },
  {
    id: "regime-detection",
    title: "Regime Detection",
    desc: "Markov switching models, change point detection, and structural break analysis for identifying market regime changes.",
    category: "analysis",
    complexity: 3,
    tags: ["Markov Switching", "Change Points", "Structural Breaks"],
    icon: "Beaker",
  },
  {
    id: "seasonality-analysis",
    title: "Seasonality Analysis",
    desc: "Calendar effects, seasonal patterns, and cyclical analysis for identifying time-based trading opportunities.",
    category: "analysis",
    complexity: 2,
    tags: ["Calendar Effects", "Seasonal Patterns", "Cycles"],
    icon: "Beaker",
  },
  {
    id: "momentum-analysis",
    title: "Momentum Analysis",
    desc: "Cross-sectional and time-series momentum, momentum crashes, and momentum factor construction for systematic strategies.",
    category: "analysis",
    complexity: 2,
    tags: ["Cross-Sectional", "Time-Series", "Factor Construction"],
    icon: "Beaker",
  },
  {
    id: "mean-reversion",
    title: "Mean Reversion Analysis",
    desc: "Statistical tests for mean reversion, half-life estimation, and optimal entry/exit points for mean-reverting strategies.",
    category: "analysis",
    complexity: 2,
    tags: ["Half-Life", "ADF Test", "Ornstein-Uhlenbeck"],
    icon: "Beaker",
  },
  {
    id: "cointegration",
    title: "Cointegration Analysis",
    desc: "Johansen test, Engle-Granger method, and error correction models for pairs trading and statistical arbitrage.",
    category: "analysis",
    complexity: 3,
    tags: ["Johansen Test", "Error Correction", "Pairs Trading"],
    icon: "Beaker",
  },
  {
    id: "principal-component",
    title: "Principal Component Analysis",
    desc: "Dimensionality reduction, factor extraction, and yield curve analysis using PCA for risk management and strategy development.",
    category: "analysis",
    complexity: 2,
    tags: ["Dimensionality Reduction", "Factor Extraction", "Yield Curve"],
    icon: "Beaker",
  },
  {
    id: "independent-component",
    title: "Independent Component Analysis",
    desc: "Blind source separation and independent factor identification for uncovering hidden market drivers and risk factors.",
    category: "analysis",
    complexity: 3,
    tags: ["Source Separation", "Independent Factors", "Hidden Drivers"],
    icon: "Beaker",
  },
  {
    id: "granger-causality",
    title: "Granger Causality",
    desc: "Statistical tests to determine if one time series can predict another, useful for lead-lag relationships and market efficiency.",
    category: "analysis",
    complexity: 3,
    tags: ["Causality Testing", "Lead-Lag", "Predictability"],
    icon: "Beaker",
  },
  {
    id: "var-models",
    title: "Vector Autoregression (VAR)",
    desc: "Multivariate time series models for analyzing dynamic relationships between multiple financial variables.",
    category: "analysis",
    complexity: 3,
    tags: ["Multivariate", "Dynamic Relationships", "Impulse Response"],
    icon: "Beaker",
  },
  {
    id: "garch-family",
    title: "GARCH Family Models",
    desc: "GARCH, EGARCH, GJR-GARCH, and FIGARCH models for volatility clustering, asymmetric effects, and long memory.",
    category: "analysis",
    complexity: 3,
    tags: ["Volatility Clustering", "Asymmetric Effects", "Long Memory"],
    icon: "Beaker",
  },
  {
    id: "stochastic-volatility",
    title: "Stochastic Volatility Models",
    desc: "Heston, Hull-White, and SABR models for options pricing and volatility surface modeling.",
    category: "analysis",
    complexity: 3,
    tags: ["Heston Model", "Hull-White", "SABR"],
    icon: "Beaker",
  },
  {
    id: "jump-diffusion",
    title: "Jump-Diffusion Models",
    desc: "Merton jump-diffusion and Kou models for capturing sudden price movements and tail risk in options pricing.",
    category: "analysis",
    complexity: 3,
    tags: ["Merton Model", "Kou Model", "Tail Risk"],
    icon: "Beaker",
  },
  {
    id: "levy-processes",
    title: "Lévy Processes",
    desc: "Non-Gaussian models including Variance Gamma, NIG, and CGMY for heavy-tailed return distributions.",
    category: "analysis",
    complexity: 3,
    tags: ["Variance Gamma", "NIG", "Heavy Tails"],
    icon: "Beaker",
  },
  {
    id: "extreme-value-theory",
    title: "Extreme Value Theory",
    desc: "Statistical methods for modeling extreme market events, tail risk, and rare event probabilities.",
    category: "analysis",
    complexity: 3,
    tags: ["Tail Risk", "Extreme Events", "GPD"],
    icon: "Beaker",
  },
  {
    id: "copula-analysis",
    title: "Copula Analysis",
    desc: "Gaussian, t-copula, and Archimedean copulas for modeling complex dependencies between assets.",
    category: "analysis",
    complexity: 3,
    tags: ["Gaussian Copula", "t-Copula", "Archimedean"],
    icon: "Beaker",
  },
  {
    id: "vine-copulas",
    title: "Vine Copulas",
    desc: "C-vine and D-vine copulas for high-dimensional dependency modeling in portfolio construction.",
    category: "analysis",
    complexity: 3,
    tags: ["C-vine", "D-vine", "High-Dimensional"],
    icon: "Beaker",
  },
  {
    id: "state-space-models",
    title: "State Space Models",
    desc: "Kalman filters, particle filters, and unscented Kalman filters for dynamic parameter estimation.",
    category: "analysis",
    complexity: 3,
    tags: ["Kalman Filter", "Particle Filter", "Dynamic Parameters"],
    icon: "Beaker",
  },
  {
    id: "threshold-models",
    title: "Threshold Models",
    desc: "TAR, SETAR, and LSTAR models for non-linear time series with regime-dependent behavior.",
    category: "analysis",
    complexity: 3,
    tags: ["TAR", "SETAR", "Non-linear"],
    icon: "Beaker",
  },
  {
    id: "smooth-transition",
    title: "Smooth Transition Models",
    desc: "STAR and LSTAR models for gradual regime changes and smooth non-linearities in financial data.",
    category: "analysis",
    complexity: 3,
    tags: ["STAR", "LSTAR", "Smooth Transitions"],
    icon: "Beaker",
  },
  {
    id: "functional-data-analysis",
    title: "Functional Data Analysis",
    desc: "FDA techniques for analyzing yield curves, volatility surfaces, and other functional financial data.",
    category: "analysis",
    complexity: 3,
    tags: ["FDA", "Yield Curves", "Functional Data"],
    icon: "Beaker",
  },
  {
    id: "robust-statistics",
    title: "Robust Statistics",
    desc: "M-estimators, robust regression, and outlier-resistant methods for handling data contamination.",
    category: "analysis",
    complexity: 2,
    tags: ["M-estimators", "Robust Regression", "Outliers"],
    icon: "Beaker",
  },
  {
    id: "bootstrap-methods",
    title: "Bootstrap Methods",
    desc: "Block bootstrap, stationary bootstrap, and circular bootstrap for time series confidence intervals.",
    category: "analysis",
    complexity: 2,
    tags: ["Block Bootstrap", "Stationary Bootstrap", "Confidence Intervals"],
    icon: "Beaker",
  },
  {
    id: "empirical-mode",
    title: "Empirical Mode Decomposition",
    desc: "EMD and EEMD for adaptive decomposition of non-stationary financial time series into intrinsic modes.",
    category: "analysis",
    complexity: 3,
    tags: ["EMD", "EEMD", "Intrinsic Modes"],
    icon: "Beaker",
  },
  {
    id: "singular-spectrum",
    title: "Singular Spectrum Analysis",
    desc: "SSA for trend extraction, noise reduction, and forecasting in non-parametric time series analysis.",
    category: "analysis",
    complexity: 3,
    tags: ["SSA", "Trend Extraction", "Non-parametric"],
    icon: "Beaker",
  },
  {
    id: "recurrence-quantification",
    title: "Recurrence Quantification Analysis",
    desc: "RQA for detecting recurring patterns, determinism, and complexity in financial time series.",
    category: "analysis",
    complexity: 3,
    tags: ["RQA", "Recurring Patterns", "Determinism"],
    icon: "Beaker",
  },
  {
    id: "detrended-fluctuation",
    title: "Detrended Fluctuation Analysis",
    desc: "DFA for measuring long-range correlations and scaling properties in financial time series.",
    category: "analysis",
    complexity: 3,
    tags: ["DFA", "Long-range Correlations", "Scaling"],
    icon: "Beaker",
  },
  {
    id: "spectral",
    title: "Spectral Analysis",
    desc: "Frequency domain analysis to identify cycles, seasonality, and periodic patterns in financial time series data.",
    category: "analysis",
    complexity: 3,
    tags: ["FFT", "Periodogram", "Cycles"],
    icon: "Beaker",
  },
  {
    id: "fourier-analysis",
    title: "Fourier Analysis",
    desc: "Fast Fourier Transform (FFT) and discrete Fourier transform for frequency domain analysis of price patterns.",
    category: "analysis",
    complexity: 3,
    tags: ["FFT", "Frequency Domain", "Harmonic Analysis"],
    icon: "Beaker",
  },
  {
    id: "time-series-decomposition",
    title: "Time Series Decomposition",
    desc: "Seasonal decomposition, trend extraction, and cyclical component analysis for understanding market patterns.",
    category: "analysis",
    complexity: 2,
    tags: ["Seasonal Decomposition", "Trend Analysis", "Cyclical Patterns"],
    icon: "Beaker",
  },
  {
    id: "cross-correlation",
    title: "Cross-Correlation Analysis",
    desc: "Lead-lag relationships, cross-correlations, and coherence analysis between different financial time series.",
    category: "analysis",
    complexity: 2,
    tags: ["Lead-Lag", "Cross-Correlation", "Coherence"],
    icon: "Beaker",
  },
  {
    id: "autocorrelation",
    title: "Autocorrelation Analysis",
    desc: "Serial correlation, autocorrelation functions, and partial autocorrelation for time series modeling.",
    category: "analysis",
    complexity: 2,
    tags: ["Serial Correlation", "ACF", "PACF"],
    icon: "Beaker",
  },

  // ML/AI CATEGORY - Machine learning and AI techniques (25 ingredients)
  {
    id: "supervised",
    title: "Supervised Learning",
    desc: "Classification and regression models for price prediction. Includes Random Forests, XGBoost, and Support Vector Machines trained on labeled data.",
    category: "ml",
    complexity: 2,
    tags: ["Random Forest", "XGBoost", "SVM"],
    icon: "BrainCircuit",
  },
  {
    id: "deeplearning",
    title: "Deep Learning",
    desc: "Neural networks including LSTMs for time series, CNNs for pattern recognition, and Transformers for market regime detection.",
    category: "ml",
    complexity: 3,
    tags: ["LSTM", "Transformers", "Autoencoders"],
    icon: "BrainCircuit",
  },
  {
    id: "reinforcement",
    title: "Reinforcement Learning",
    desc: "Agents that learn optimal trading policies through interaction with markets. Uses Q-learning, DQN, and Policy Gradient methods.",
    category: "ml",
    complexity: 3,
    tags: ["Q-Learning", "PPO", "Adaptive"],
    icon: "BrainCircuit",
  },
  {
    id: "nlp",
    title: "NLP & Sentiment",
    desc: "Natural language processing for news, social media, and earnings calls. Extracts market sentiment and trading signals from text data.",
    category: "ml",
    complexity: 2,
    tags: ["BERT", "Sentiment", "News Analysis"],
    icon: "BrainCircuit",
  },
  {
    id: "gnn",
    title: "Graph Neural Networks",
    desc: "Model complex relationships between assets using graph structures. Captures market connectivity, sector relationships, and contagion effects.",
    category: "ml",
    complexity: 3,
    tags: ["Network Analysis", "Contagion", "GCN"],
    icon: "BrainCircuit",
  },
  {
    id: "gan",
    title: "GANs for Finance",
    desc: "Generative Adversarial Networks for synthetic data generation, scenario simulation, and improving backtest robustness.",
    category: "ml",
    complexity: 3,
    tags: ["Synthetic Data", "Simulation", "WGAN"],
    icon: "BrainCircuit",
  },
  {
    id: "ensemble-methods",
    title: "Ensemble Methods",
    desc: "Combine multiple models using bagging, boosting, and stacking for improved prediction accuracy and robustness.",
    category: "ml",
    complexity: 2,
    tags: ["Bagging", "Boosting", "Stacking"],
    icon: "BrainCircuit",
  },
  {
    id: "unsupervised",
    title: "Unsupervised Learning",
    desc: "Clustering, anomaly detection, and pattern discovery without labeled data. K-means, DBSCAN, and isolation forests.",
    category: "ml",
    complexity: 2,
    tags: ["Clustering", "Anomaly Detection", "Pattern Discovery"],
    icon: "BrainCircuit",
  },
  {
    id: "feature-engineering",
    title: "Feature Engineering",
    desc: "Automated feature selection, creation, and transformation using genetic algorithms and statistical methods.",
    category: "ml",
    complexity: 2,
    tags: ["Feature Selection", "Genetic Algorithms", "Transformation"],
    icon: "BrainCircuit",
  },
  {
    id: "hyperparameter-optimization",
    title: "Hyperparameter Optimization",
    desc: "Bayesian optimization, grid search, and random search for optimal model parameters and architecture selection.",
    category: "ml",
    complexity: 2,
    tags: ["Bayesian Optimization", "Grid Search", "Architecture"],
    icon: "BrainCircuit",
  },
  {
    id: "online-learning",
    title: "Online Learning",
    desc: "Adaptive algorithms that learn continuously from streaming data without retraining from scratch.",
    category: "ml",
    complexity: 3,
    tags: ["Streaming Data", "Adaptive", "Continuous Learning"],
    icon: "BrainCircuit",
  },
  {
    id: "transfer-learning",
    title: "Transfer Learning",
    desc: "Apply pre-trained models from one market or timeframe to another, reducing training time and data requirements.",
    category: "ml",
    complexity: 2,
    tags: ["Pre-trained Models", "Domain Adaptation", "Fine-tuning"],
    icon: "BrainCircuit",
  },
  {
    id: "federated-learning",
    title: "Federated Learning",
    desc: "Train models across multiple institutions without sharing sensitive data, enabling collaborative alpha generation.",
    category: "ml",
    complexity: 3,
    tags: ["Privacy Preserving", "Collaborative", "Distributed"],
    icon: "BrainCircuit",
  },
  {
    id: "explainable-ai",
    title: "Explainable AI",
    desc: "SHAP values, LIME, and other techniques to interpret and explain ML model decisions for regulatory compliance.",
    category: "ml",
    complexity: 2,
    tags: ["SHAP", "LIME", "Model Interpretation"],
    icon: "BrainCircuit",
  },
  {
    id: "computer-vision",
    title: "Computer Vision",
    desc: "Chart pattern recognition, candlestick pattern detection, and visual analysis of market data using CNNs.",
    category: "ml",
    complexity: 3,
    tags: ["Chart Patterns", "CNNs", "Visual Analysis"],
    icon: "BrainCircuit",
  },
  {
    id: "attention-mechanisms",
    title: "Attention Mechanisms",
    desc: "Self-attention, multi-head attention, and transformer architectures for sequential financial data modeling.",
    category: "ml",
    complexity: 3,
    tags: ["Self-Attention", "Multi-Head", "Sequential Data"],
    icon: "BrainCircuit",
  },
  {
    id: "variational-autoencoders",
    title: "Variational Autoencoders",
    desc: "VAEs for dimensionality reduction, anomaly detection, and generating synthetic financial data.",
    category: "ml",
    complexity: 3,
    tags: ["VAE", "Dimensionality Reduction", "Synthetic Data"],
    icon: "BrainCircuit",
  },
  {
    id: "neural-odes",
    title: "Neural ODEs",
    desc: "Continuous-time neural networks for modeling irregular time series and dynamic systems in finance.",
    category: "ml",
    complexity: 3,
    tags: ["Continuous Time", "Irregular Series", "Dynamic Systems"],
    icon: "BrainCircuit",
  },
  {
    id: "meta-learning",
    title: "Meta-Learning",
    desc: "Learning to learn algorithms that quickly adapt to new markets or trading regimes with minimal data.",
    category: "ml",
    complexity: 3,
    tags: ["Few-Shot Learning", "Quick Adaptation", "MAML"],
    icon: "BrainCircuit",
  },
  {
    id: "adversarial-training",
    title: "Adversarial Training",
    desc: "Robust model training against adversarial attacks and market manipulation attempts.",
    category: "ml",
    complexity: 3,
    tags: ["Adversarial Attacks", "Robust Training", "Market Manipulation"],
    icon: "BrainCircuit",
  },
  {
    id: "causal-inference",
    title: "Causal Inference",
    desc: "Causal discovery, instrumental variables, and do-calculus for understanding true causal relationships in markets.",
    category: "ml",
    complexity: 3,
    tags: ["Causal Discovery", "Instrumental Variables", "Do-Calculus"],
    icon: "BrainCircuit",
  },
  {
    id: "multi-task-learning",
    title: "Multi-Task Learning",
    desc: "Shared representations across multiple prediction tasks like price, volatility, and volume forecasting.",
    category: "ml",
    complexity: 3,
    tags: ["Shared Representations", "Multiple Tasks", "Joint Learning"],
    icon: "BrainCircuit",
  },
  {
    id: "continual-learning",
    title: "Continual Learning",
    desc: "Learning new tasks without forgetting previous ones, crucial for adapting to evolving market conditions.",
    category: "ml",
    complexity: 3,
    tags: ["Catastrophic Forgetting", "Lifelong Learning", "Market Evolution"],
    icon: "BrainCircuit",
  },
  {
    id: "neural-architecture-search",
    title: "Neural Architecture Search",
    desc: "Automated design of neural network architectures optimized for specific financial prediction tasks.",
    category: "ml",
    complexity: 3,
    tags: ["Architecture Search", "AutoML", "Optimization"],
    icon: "BrainCircuit",
  },
  {
    id: "probabilistic-programming",
    title: "Probabilistic Programming",
    desc: "Bayesian neural networks and probabilistic models for uncertainty quantification in predictions.",
    category: "ml",
    complexity: 3,
    tags: ["Bayesian Networks", "Uncertainty", "Probabilistic Models"],
    icon: "BrainCircuit",
  },

  // RISK CATEGORY - Risk management techniques (20 ingredients)
  {
    id: "position",
    title: "Position Sizing",
    desc: "Optimal capital allocation using Kelly Criterion, fixed fractional, or volatility-based methods to maximize returns while controlling risk.",
    category: "risk",
    complexity: 2,
    tags: ["Kelly Criterion", "Risk Parity", "Volatility Sizing"],
    icon: "ShieldCheck",
  },
  {
    id: "portfolio",
    title: "Portfolio Optimization",
    desc: "Modern portfolio theory, mean-variance optimization, Black-Litterman models, and risk budgeting for multi-asset allocation.",
    category: "risk",
    complexity: 3,
    tags: ["Markowitz", "Black-Litterman", "Efficient Frontier"],
    icon: "ShieldCheck",
  },
  {
    id: "metrics",
    title: "Risk Metrics",
    desc: "VaR, CVaR, Sharpe ratio, maximum drawdown, and other metrics to measure and monitor portfolio risk in real-time.",
    category: "risk",
    complexity: 1,
    tags: ["Value at Risk", "Sharpe Ratio", "Drawdown"],
    icon: "ShieldCheck",
  },
  {
    id: "hedging",
    title: "Hedging Strategies",
    desc: "Dynamic hedging, options overlays, tail risk protection, and correlation hedges to protect portfolios during market stress.",
    category: "risk",
    complexity: 3,
    tags: ["Options Hedging", "Tail Risk", "Delta Neutral"],
    icon: "ShieldCheck",
  },
  {
    id: "stress",
    title: "Stress Testing",
    desc: "Scenario analysis, historical stress tests, and Monte Carlo simulations to evaluate portfolio performance under extreme market conditions.",
    category: "risk",
    complexity: 2,
    tags: ["Scenarios", "Black Swan", "Tail Events"],
    icon: "ShieldCheck",
  },
  {
    id: "liquidity",
    title: "Liquidity Risk",
    desc: "Model market impact, slippage, and liquidation costs. Critical for large positions and during market stress when liquidity evaporates.",
    category: "risk",
    complexity: 3,
    tags: ["Market Impact", "Slippage", "Liquidation"],
    icon: "ShieldCheck",
  },
  {
    id: "credit-risk",
    title: "Credit Risk Management",
    desc: "Counterparty risk assessment, credit exposure limits, and collateral management for derivatives and lending strategies.",
    category: "risk",
    complexity: 2,
    tags: ["Counterparty Risk", "Exposure Limits", "Collateral"],
    icon: "ShieldCheck",
  },
  {
    id: "operational-risk",
    title: "Operational Risk",
    desc: "System failures, human errors, and process breakdowns. Includes backup systems, error handling, and business continuity planning.",
    category: "risk",
    complexity: 2,
    tags: ["System Failures", "Error Handling", "Business Continuity"],
    icon: "ShieldCheck",
  },
  {
    id: "model-risk",
    title: "Model Risk Management",
    desc: "Model validation, backtesting, and monitoring for model degradation and overfitting in quantitative strategies.",
    category: "risk",
    complexity: 3,
    tags: ["Model Validation", "Overfitting", "Degradation"],
    icon: "ShieldCheck",
  },
  {
    id: "concentration-risk",
    title: "Concentration Risk",
    desc: "Diversification metrics, concentration limits, and sector/geographic exposure management to avoid over-concentration.",
    category: "risk",
    complexity: 2,
    tags: ["Diversification", "Concentration Limits", "Sector Exposure"],
    icon: "ShieldCheck",
  },
  {
    id: "tail-risk",
    title: "Tail Risk Management",
    desc: "Extreme value theory, tail hedging strategies, and black swan protection for managing rare but severe market events.",
    category: "risk",
    complexity: 3,
    tags: ["Extreme Value Theory", "Black Swan", "Tail Hedging"],
    icon: "ShieldCheck",
  },
  {
    id: "correlation-risk",
    title: "Correlation Risk",
    desc: "Monitor correlation breakdowns during stress, correlation clustering, and diversification failure in crisis periods.",
    category: "risk",
    complexity: 2,
    tags: ["Correlation Breakdown", "Diversification Failure", "Crisis"],
    icon: "ShieldCheck",
  },
  {
    id: "volatility-risk",
    title: "Volatility Risk",
    desc: "Volatility forecasting, vol-of-vol modeling, and volatility regime changes for options and volatility strategies.",
    category: "risk",
    complexity: 3,
    tags: ["Vol Forecasting", "Vol-of-Vol", "Regime Changes"],
    icon: "ShieldCheck",
  },
  {
    id: "regulatory-risk",
    title: "Regulatory Risk",
    desc: "Compliance monitoring, regulatory change impact assessment, and position limits for regulatory adherence.",
    category: "risk",
    complexity: 2,
    tags: ["Compliance", "Position Limits", "Regulatory Changes"],
    icon: "ShieldCheck",
  },
  {
    id: "currency-risk",
    title: "Currency Risk",
    desc: "FX hedging, currency exposure measurement, and multi-currency portfolio risk management for global strategies.",
    category: "risk",
    complexity: 2,
    tags: ["FX Hedging", "Currency Exposure", "Multi-Currency"],
    icon: "ShieldCheck",
  },
  {
    id: "systemic-risk",
    title: "Systemic Risk",
    desc: "Network analysis of financial system interconnectedness, contagion modeling, and systemic risk indicators.",
    category: "risk",
    complexity: 3,
    tags: ["Network Analysis", "Contagion", "Interconnectedness"],
    icon: "ShieldCheck",
  },
  {
    id: "climate-risk",
    title: "Climate Risk",
    desc: "Physical and transition climate risks, carbon pricing, and ESG factor integration in risk models.",
    category: "risk",
    complexity: 2,
    tags: ["Climate Risk", "Carbon Pricing", "ESG"],
    icon: "ShieldCheck",
  },
  {
    id: "cyber-risk",
    title: "Cyber Risk",
    desc: "Cybersecurity threats, data breaches, and technology risk management for trading systems.",
    category: "risk",
    complexity: 2,
    tags: ["Cybersecurity", "Data Breaches", "Technology Risk"],
    icon: "ShieldCheck",
  },
  {
    id: "behavioral-risk",
    title: "Behavioral Risk",
    desc: "Cognitive biases, herding behavior, and behavioral finance factors that affect risk perception and decision-making.",
    category: "risk",
    complexity: 2,
    tags: ["Cognitive Biases", "Herding", "Behavioral Finance"],
    icon: "ShieldCheck",
  },
  {
    id: "reputational-risk",
    title: "Reputational Risk",
    desc: "Brand damage, ESG controversies, and social media sentiment impact on investment performance.",
    category: "risk",
    complexity: 2,
    tags: ["Brand Damage", "ESG Controversies", "Social Media"],
    icon: "ShieldCheck",
  },

  // EXECUTION CATEGORY - Trading execution and infrastructure (20 ingredients)
  {
    id: "algos",
    title: "Execution Algorithms",
    desc: "TWAP, VWAP, Implementation Shortfall, and other algorithms to minimize market impact and achieve best execution.",
    category: "execution",
    complexity: 2,
    tags: ["TWAP", "VWAP", "Iceberg"],
    icon: "Rocket",
  },
  {
    id: "routing",
    title: "Smart Order Routing",
    desc: "Intelligent routing across multiple venues, dark pools, and exchanges to find best prices and hidden liquidity.",
    category: "execution",
    complexity: 3,
    tags: ["Multi-Venue", "Dark Pools", "Best Execution"],
    icon: "Rocket",
  },
  {
    id: "latency",
    title: "Latency Optimization",
    desc: "Co-location, network optimization, FPGA acceleration, and kernel bypass for microsecond-level execution speed.",
    category: "execution",
    complexity: 3,
    tags: ["Co-location", "FPGA", "Low Latency"],
    icon: "Rocket",
  },
  {
    id: "infrastructure",
    title: "Trading Infrastructure",
    desc: "FIX connectivity, API integration, message queues, and databases optimized for high-throughput trading systems.",
    category: "execution",
    complexity: 2,
    tags: ["FIX Protocol", "REST/WebSocket", "Message Queues"],
    icon: "Rocket",
  },
  {
    id: "tca",
    title: "Transaction Cost Analysis",
    desc: "Pre-trade and post-trade analysis to measure execution quality, slippage, and optimize future trades.",
    category: "execution",
    complexity: 2,
    tags: ["Slippage Analysis", "Cost Attribution", "Benchmarking"],
    icon: "Rocket",
  },
  {
    id: "matching",
    title: "Matching Engine",
    desc: "Understanding exchange matching algorithms: FIFO, Pro-Rata, and hybrid models. Critical for HFT queue position strategies.",
    category: "execution",
    complexity: 3,
    tags: ["FIFO", "Pro-Rata", "Queue Priority"],
    icon: "Rocket",
  },
  {
    id: "order-management",
    title: "Order Management System",
    desc: "Centralized order routing, position tracking, and risk controls with real-time monitoring and alerting capabilities.",
    category: "execution",
    complexity: 2,
    tags: ["Order Routing", "Position Tracking", "Risk Controls"],
    icon: "Rocket",
  },
  {
    id: "portfolio-management",
    title: "Portfolio Management System",
    desc: "Real-time P&L calculation, risk monitoring, and portfolio analytics with multi-asset class support.",
    category: "execution",
    complexity: 2,
    tags: ["P&L Calculation", "Risk Monitoring", "Multi-Asset"],
    icon: "Rocket",
  },
  {
    id: "market-data",
    title: "Market Data Systems",
    desc: "High-performance market data feeds, normalization, and distribution with microsecond timestamps and conflation.",
    category: "execution",
    complexity: 3,
    tags: ["Market Data Feeds", "Normalization", "Conflation"],
    icon: "Rocket",
  },
  {
    id: "risk-controls",
    title: "Real-time Risk Controls",
    desc: "Pre-trade and post-trade risk checks, position limits, and automated kill switches for risk management.",
    category: "execution",
    complexity: 2,
    tags: ["Pre-trade Checks", "Position Limits", "Kill Switches"],
    icon: "Rocket",
  },
  {
    id: "execution-venues",
    title: "Execution Venues",
    desc: "Exchange connectivity, dark pool access, and alternative trading systems (ATS) for optimal execution.",
    category: "execution",
    complexity: 2,
    tags: ["Exchange Connectivity", "Dark Pools", "ATS"],
    icon: "Rocket",
  },
  {
    id: "prime-brokerage",
    title: "Prime Brokerage Integration",
    desc: "Prime broker connectivity, margin management, and securities lending for institutional trading operations.",
    category: "execution",
    complexity: 2,
    tags: ["Prime Broker", "Margin Management", "Securities Lending"],
    icon: "Rocket",
  },
  {
    id: "settlement",
    title: "Settlement & Clearing",
    desc: "Trade settlement, clearing house integration, and post-trade processing for multi-asset class trading.",
    category: "execution",
    complexity: 2,
    tags: ["Trade Settlement", "Clearing House", "Post-Trade"],
    icon: "Rocket",
  },
  {
    id: "compliance-monitoring",
    title: "Compliance Monitoring",
    desc: "Real-time compliance checks, regulatory reporting, and audit trails for institutional trading requirements.",
    category: "execution",
    complexity: 2,
    tags: ["Compliance Checks", "Regulatory Reporting", "Audit Trails"],
    icon: "Rocket",
  },
  {
    id: "cross-asset",
    title: "Cross-Asset Trading",
    desc: "Unified trading platform for equities, fixed income, FX, commodities, and derivatives with cross-margining.",
    category: "execution",
    complexity: 3,
    tags: ["Multi-Asset", "Cross-Margining", "Unified Platform"],
    icon: "Rocket",
  },
  {
    id: "blockchain-execution",
    title: "Blockchain Execution",
    desc: "DeFi protocol integration, smart contract execution, and decentralized exchange connectivity.",
    category: "execution",
    complexity: 3,
    tags: ["DeFi", "Smart Contracts", "DEX"],
    icon: "Rocket",
  },
  {
    id: "cloud-infrastructure",
    title: "Cloud Infrastructure",
    desc: "Scalable cloud-based trading systems, auto-scaling, and distributed computing for global operations.",
    category: "execution",
    complexity: 2,
    tags: ["Cloud Computing", "Auto-scaling", "Distributed"],
    icon: "Rocket",
  },
  {
    id: "microservices",
    title: "Microservices Architecture",
    desc: "Containerized trading services, API gateways, and service mesh for scalable and maintainable systems.",
    category: "execution",
    complexity: 3,
    tags: ["Containers", "API Gateway", "Service Mesh"],
    icon: "Rocket",
  },
  {
    id: "event-driven",
    title: "Event-Driven Architecture",
    desc: "Event sourcing, CQRS, and message-driven systems for real-time trading event processing.",
    category: "execution",
    complexity: 3,
    tags: ["Event Sourcing", "CQRS", "Message-Driven"],
    icon: "Rocket",
  },
  {
    id: "disaster-recovery",
    title: "Disaster Recovery",
    desc: "Hot standby systems, data replication, and failover mechanisms for business continuity.",
    category: "execution",
    complexity: 2,
    tags: ["Hot Standby", "Data Replication", "Failover"],
    icon: "Rocket",
  },

  // ADVANCED CATEGORY - Sophisticated mathematical and computational techniques (20 ingredients)
  {
    id: "kalman",
    title: "Kalman Filters",
    desc: "Dynamic state estimation for hedge ratios, signal extraction from noisy data, and adaptive parameter updating in real-time.",
    category: "advanced",
    complexity: 3,
    tags: ["State Estimation", "Noise Filtering", "Adaptive"],
    icon: "Bot",
  },
  {
    id: "hmm",
    title: "Hidden Markov Models",
    desc: "Regime detection and switching models to identify market states and adapt strategies to changing conditions automatically.",
    category: "advanced",
    complexity: 3,
    tags: ["Regime Detection", "State Switching", "Baum-Welch"],
    icon: "Bot",
  },
  {
    id: "copula",
    title: "Copula Models",
    desc: "Model complex non-linear dependencies between assets, especially useful for tail risk and extreme event correlation.",
    category: "advanced",
    complexity: 3,
    tags: ["Tail Dependence", "Non-Linear", "Risk Modeling"],
    icon: "Bot",
  },
  {
    id: "mle",
    title: "Maximum Likelihood",
    desc: "Parameter estimation for complex models using MLE. Essential for calibrating stochastic volatility models and regime-switching systems.",
    category: "advanced",
    complexity: 3,
    tags: ["Optimization", "Calibration", "Statistical Inference"],
    icon: "Bot",
  },
  {
    id: "hawkes",
    title: "Hawkes Processes",
    desc: "Self-exciting point processes for modeling clustered events like trades, order arrivals, and volatility bursts in high-frequency data.",
    category: "advanced",
    complexity: 3,
    tags: ["Point Process", "Self-Exciting", "HFT"],
    icon: "Bot",
  },
  {
    id: "stochastic-calculus",
    title: "Stochastic Calculus",
    desc: "Ito's lemma, stochastic differential equations, and continuous-time finance for derivatives pricing and hedging.",
    category: "advanced",
    complexity: 3,
    tags: ["Ito's Lemma", "SDE", "Continuous Time"],
    icon: "Bot",
  },
  {
    id: "monte-carlo",
    title: "Monte Carlo Methods",
    desc: "Simulation techniques for option pricing, risk assessment, and scenario analysis with variance reduction methods.",
    category: "advanced",
    complexity: 3,
    tags: ["Simulation", "Variance Reduction", "Scenario Analysis"],
    icon: "Bot",
  },
  {
    id: "bayesian-methods",
    title: "Bayesian Methods",
    desc: "Bayesian inference, MCMC sampling, and probabilistic programming for parameter uncertainty and model selection.",
    category: "advanced",
    complexity: 3,
    tags: ["Bayesian Inference", "MCMC", "Probabilistic Programming"],
    icon: "Bot",
  },
  {
    id: "optimal-control",
    title: "Optimal Control Theory",
    desc: "Dynamic programming, Hamilton-Jacobi-Bellman equations, and optimal stopping for portfolio optimization and execution.",
    category: "advanced",
    complexity: 3,
    tags: ["Dynamic Programming", "HJB", "Optimal Stopping"],
    icon: "Bot",
  },
  {
    id: "game-theory",
    title: "Game Theory",
    desc: "Strategic interactions in markets, auction theory, and mechanism design for understanding market participant behavior.",
    category: "advanced",
    complexity: 3,
    tags: ["Strategic Interactions", "Auction Theory", "Mechanism Design"],
    icon: "Bot",
  },
  {
    id: "information-theory",
    title: "Information Theory",
    desc: "Mutual information, transfer entropy, and information flow analysis for understanding market efficiency and causality.",
    category: "advanced",
    complexity: 3,
    tags: ["Mutual Information", "Transfer Entropy", "Causality"],
    icon: "Bot",
  },
  {
    id: "network-theory",
    title: "Network Theory",
    desc: "Graph analysis of market relationships, systemic risk, and contagion effects using network centrality measures.",
    category: "advanced",
    complexity: 3,
    tags: ["Graph Analysis", "Systemic Risk", "Centrality Measures"],
    icon: "Bot",
  },
  {
    id: "topology",
    title: "Topological Data Analysis",
    desc: "Persistent homology and topological features for identifying market structure and regime changes in high-dimensional data.",
    category: "advanced",
    complexity: 3,
    tags: ["Persistent Homology", "Market Structure", "High-Dimensional"],
    icon: "Bot",
  },
  {
    id: "quantum-computing",
    title: "Quantum Computing",
    desc: "Quantum algorithms for portfolio optimization, Monte Carlo acceleration, and machine learning in financial applications.",
    category: "advanced",
    complexity: 3,
    tags: ["Quantum Algorithms", "Portfolio Optimization", "Quantum ML"],
    icon: "Bot",
  },
  {
    id: "differential-geometry",
    title: "Differential Geometry",
    desc: "Manifold learning, Riemannian geometry, and geometric methods for high-dimensional financial data analysis.",
    category: "advanced",
    complexity: 3,
    tags: ["Manifold Learning", "Riemannian", "High-Dimensional"],
    icon: "Bot",
  },
  {
    id: "algebraic-topology",
    title: "Algebraic Topology",
    desc: "Homology groups, Betti numbers, and topological invariants for market structure analysis and regime detection.",
    category: "advanced",
    complexity: 3,
    tags: ["Homology", "Betti Numbers", "Topological Invariants"],
    icon: "Bot",
  },
  {
    id: "martingale-theory",
    title: "Martingale Theory",
    desc: "Martingales, stopping times, and optional stopping theorem for derivatives pricing and risk-neutral valuation.",
    category: "advanced",
    complexity: 3,
    tags: ["Martingales", "Stopping Times", "Risk-Neutral"],
    icon: "Bot",
  },
  {
    id: "ergodic-theory",
    title: "Ergodic Theory",
    desc: "Dynamical systems, invariant measures, and long-term behavior analysis for market dynamics.",
    category: "advanced",
    complexity: 3,
    tags: ["Dynamical Systems", "Invariant Measures", "Long-term Behavior"],
    icon: "Bot",
  },
  {
    id: "chaos-theory",
    title: "Chaos Theory",
    desc: "Nonlinear dynamics, strange attractors, and sensitive dependence for modeling complex market behavior.",
    category: "advanced",
    complexity: 3,
    tags: ["Nonlinear Dynamics", "Strange Attractors", "Sensitive Dependence"],
    icon: "Bot",
  },
  {
    id: "tensor-methods",
    title: "Tensor Methods",
    desc: "Tensor decomposition, multilinear algebra, and tensor networks for high-dimensional financial data analysis.",
    category: "advanced",
    complexity: 3,
    tags: ["Tensor Decomposition", "Multilinear Algebra", "Tensor Networks"],
    icon: "Bot",
  },
]

export const strategies: Strategy[] = [
  {
    id: "adaptive-momentum",
    title: "Adaptive Momentum Breakout",
    desc: "Multi-timeframe momentum strategy with dynamic parameter adjustment based on market regime. Combines price breakouts, volume surge detection, and volatility filters to capture strong directional moves while avoiding false signals in choppy markets.",
    type: "Trend Following",
    category: "momentum",
    difficulty: 3,
    components: ["OHLCV Data", "Volume Profile", "ATR", "Regime Detection", "Position Sizing"],
    metrics: [
      { label: "Win Rate", value: "68%" },
      { label: "Sharpe", value: "2.3" },
      { label: "Annual Return", value: "45%" },
      { label: "Max Drawdown", value: "-12%" },
    ],
    implementation: [
      {
        title: "Multi-Timeframe Setup",
        desc: "Collect OHLCV data across 5m, 15m, 1h, 4h, and daily timeframes for trend alignment",
      },
      {
        title: "Regime Identification",
        desc: "Use Hidden Markov Model to classify market as trending, ranging, or volatile",
      },
      {
        title: "Dynamic Signal Generation",
        desc: "Adjust breakout thresholds based on regime: tight in trends, wide in ranges",
      },
      { title: "Risk Management", desc: "Volatility-based position sizing with 2% portfolio risk per trade" },
    ],
    risks: "Vulnerable to whipsaws in ranging markets. Requires robust regime detection to avoid overtrading.",
    featured: true,
  },
  {
    id: "stat-arb",
    title: "Multi-Factor Statistical Arbitrage",
    desc: "Advanced pairs trading system using cointegration, machine learning for pair selection, and Kalman filters for dynamic hedge ratio adjustment. Incorporates multiple factors including momentum, value, and microstructure signals for enhanced alpha generation.",
    type: "Market Neutral",
    category: "arbitrage",
    difficulty: 4,
    components: ["Tick Data", "Cointegration Tests", "Kalman Filter", "Factor Models", "ML Classification"],
    metrics: [
      { label: "Win Rate", value: "82%" },
      { label: "Sharpe", value: "3.1" },
      { label: "Annual Return", value: "28%" },
      { label: "Max Drawdown", value: "-8%" },
    ],
    implementation: [
      { title: "Universe Selection", desc: "Filter liquid stocks with >$10M daily volume, stable fundamentals" },
      { title: "Pair Formation", desc: "Apply Johansen test and ML clustering to identify stable pairs" },
      { title: "Dynamic Hedging", desc: "Update hedge ratios every hour using Kalman filter" },
      { title: "Multi-Factor Enhancement", desc: "Overlay momentum and microstructure signals for timing" },
    ],
    risks: "Correlation breakdown during market stress. Requires sophisticated execution to minimize costs.",
    featured: true,
  },
  {
    id: "transformer-alpha",
    title: "Transformer-Based Alpha Generation",
    desc: "State-of-the-art deep learning system using Transformer architecture for multi-modal data fusion. Combines price patterns, news sentiment, options flow, and alternative data with attention mechanisms for superior prediction accuracy.",
    type: "Machine Learning",
    category: "ml",
    difficulty: 5,
    components: ["Alternative Data", "Transformers", "NLP Sentiment", "Feature Engineering", "Ensemble Methods"],
    metrics: [
      { label: "Win Rate", value: "71%" },
      { label: "Sharpe", value: "2.8" },
      { label: "Annual Return", value: "52%" },
      { label: "Max Drawdown", value: "-15%" },
    ],
    implementation: [
      { title: "Multi-Modal Data Pipeline", desc: "Aggregate price, news, satellite, social media, and options data" },
      { title: "Feature Engineering", desc: "Create 1000+ features including technical, fundamental, and alternative" },
      { title: "Transformer Architecture", desc: "Train multi-head attention model on 5 years of data" },
      { title: "Online Learning", desc: "Continuously retrain with sliding window approach" },
    ],
    risks: "Model degradation, overfitting, and high computational costs. Requires constant monitoring.",
    featured: true,
  },
  {
    id: "fpga-mm",
    title: "FPGA-Accelerated Market Making",
    desc: "Sub-microsecond market making system with FPGA hardware acceleration. Features advanced queue position modeling, adverse selection detection, and dynamic inventory management across multiple venues simultaneously.",
    type: "High Frequency",
    category: "hft",
    difficulty: 5,
    components: ["Order Book Data", "Microstructure", "FPGA/Co-location", "Queue Models", "Inventory Control"],
    metrics: [
      { label: "Win Rate", value: "89%" },
      { label: "Sharpe", value: "4.2" },
      { label: "Trades/Day", value: "25k" },
      { label: "Max Drawdown", value: "-5%" },
    ],
    implementation: [
      { title: "Infrastructure Setup", desc: "Deploy FPGA cards in co-located servers, sub-500ns latency" },
      { title: "Microstructure Analytics", desc: "Model order flow toxicity, queue position probability" },
      { title: "Dynamic Quoting", desc: "Adjust spreads based on inventory, volatility, and toxicity" },
      { title: "Risk Controls", desc: "Hardware kill switches, position limits, loss breakers" },
    ],
    risks: "Technology arms race, regulatory changes, and adverse selection from informed traders.",
  },
  {
    id: "defi-mev",
    title: "Cross-Chain MEV Arbitrage",
    desc: "Sophisticated multi-chain arbitrage system exploiting price inefficiencies across DEXs, bridges, and lending protocols. Includes MEV protection, gas optimization, and flash loan strategies across Ethereum, BSC, Arbitrum, and Polygon.",
    type: "Cryptocurrency",
    category: "crypto",
    difficulty: 4,
    components: ["Blockchain Data", "DEX Aggregators", "Flash Loans", "MEV Protection", "Gas Optimization"],
    metrics: [
      { label: "Win Rate", value: "92%" },
      { label: "Sharpe", value: "3.7" },
      { label: "APY", value: "287%" },
      { label: "Max Drawdown", value: "-10%" },
    ],
    implementation: [
      { title: "Multi-Chain Infrastructure", desc: "Deploy contracts on ETH, BSC, Arbitrum, Polygon with bridges" },
      { title: "Price Monitoring", desc: "Real-time mempool monitoring and DEX price feeds" },
      { title: "Execution Logic", desc: "Calculate profit after gas, slippage, and bridge fees" },
      { title: "MEV Protection", desc: "Use Flashbots, private mempools, and commit-reveal schemes" },
    ],
    risks: "Smart contract vulnerabilities, bridge hacks, and regulatory uncertainty.",
  },
  {
    id: "vol-premium",
    title: "Dynamic Volatility Premium Harvesting",
    desc: "Systematic short volatility strategy with machine learning-based regime detection. Dynamically adjusts option structures and hedge ratios based on volatility forecasts, term structure, and skew analysis.",
    type: "Derivatives",
    category: "options",
    difficulty: 4,
    components: ["Options Chain", "IV Surface", "GARCH Models", "Greeks Management", "Tail Hedging"],
    metrics: [
      { label: "Win Rate", value: "74%" },
      { label: "Sharpe", value: "2.5" },
      { label: "Annual Return", value: "35%" },
      { label: "Max Drawdown", value: "-18%" },
    ],
    implementation: [
      { title: "Volatility Analysis", desc: "Compare implied vs realized vol using GARCH and ML models" },
      { title: "Structure Selection", desc: "Choose between strangles, condors, or butterflies based on skew" },
      { title: "Dynamic Delta Hedging", desc: "Rebalance delta hourly, gamma scalp intraday moves" },
      { title: "Tail Risk Management", desc: "Maintain 5-10% in far OTM puts, scale with VIX level" },
    ],
    risks: "Volatility spikes can cause severe losses. Requires sophisticated risk management.",
  },
  {
    id: "mean-reversion-etf",
    title: "ETF Mean Reversion with Flow Analysis",
    desc: "Exploits temporary price dislocations in ETFs by analyzing creation/redemption flows, premium/discount patterns, and underlying basket movements. Uses statistical arbitrage principles with enhanced execution algorithms.",
    type: "Statistical Arbitrage",
    category: "arbitrage",
    difficulty: 3,
    components: ["ETF Flow Data", "Basket Tracking", "Statistical Models", "Execution Algorithms", "Risk Controls"],
    metrics: [
      { label: "Win Rate", value: "76%" },
      { label: "Sharpe", value: "2.7" },
      { label: "Annual Return", value: "31%" },
      { label: "Max Drawdown", value: "-9%" },
    ],
    implementation: [
      { title: "Flow Monitoring", desc: "Track daily creation/redemption units and authorized participant activity" },
      { title: "Premium/Discount Analysis", desc: "Calculate real-time NAV vs market price deviations" },
      { title: "Statistical Modeling", desc: "Use Ornstein-Uhlenbeck process for mean reversion timing" },
      { title: "Execution Optimization", desc: "TWAP algorithms with market impact minimization" },
    ],
    risks: "Structural breaks in ETF mechanisms during market stress. Requires real-time NAV calculations.",
  },
  {
    id: "earnings-momentum",
    title: "Post-Earnings Announcement Drift",
    desc: "Captures the well-documented anomaly where stocks continue to move in the direction of earnings surprises for several weeks. Combines fundamental analysis, options flow, and sentiment data for enhanced signal generation.",
    type: "Event-Driven",
    category: "fundamental",
    difficulty: 3,
    components: ["Earnings Data", "Options Flow", "Analyst Revisions", "Sentiment Analysis", "Factor Models"],
    metrics: [
      { label: "Win Rate", value: "69%" },
      { label: "Sharpe", value: "2.1" },
      { label: "Annual Return", value: "38%" },
      { label: "Max Drawdown", value: "-14%" },
    ],
    implementation: [
      { title: "Earnings Calendar", desc: "Monitor upcoming earnings and historical surprise patterns" },
      { title: "Surprise Quantification", desc: "Calculate standardized earnings surprises and revenue beats" },
      { title: "Options Flow Analysis", desc: "Track unusual options activity pre and post earnings" },
      { title: "Momentum Scoring", desc: "Combine earnings surprise with analyst revision momentum" },
    ],
    risks: "Crowded trade risk as anomaly becomes well-known. Requires careful position sizing.",
  },
  {
    id: "fx-carry-momentum",
    title: "FX Carry Trade with Momentum Overlay",
    desc: "Enhanced carry trade strategy that combines interest rate differentials with currency momentum and central bank policy analysis. Uses machine learning to predict carry trade unwind events and adjust exposure dynamically.",
    type: "Currency",
    category: "macro",
    difficulty: 4,
    components: ["FX Data", "Interest Rates", "Central Bank Policy", "Momentum Indicators", "Risk Parity"],
    metrics: [
      { label: "Win Rate", value: "64%" },
      { label: "Sharpe", value: "1.9" },
      { label: "Annual Return", value: "26%" },
      { label: "Max Drawdown", value: "-22%" },
    ],
    implementation: [
      { title: "Carry Ranking", desc: "Rank currency pairs by real interest rate differentials" },
      { title: "Momentum Filter", desc: "Only enter carry trades aligned with 3-month momentum" },
      { title: "Central Bank Analysis", desc: "Monitor policy meetings and forward guidance changes" },
      { title: "Risk Management", desc: "Use volatility targeting and correlation-based position sizing" },
    ],
    risks: "Vulnerable to sudden risk-off events and central bank policy surprises. Requires global macro expertise.",
  },
  {
    id: "sector-rotation",
    title: "Macro-Driven Sector Rotation",
    desc: "Systematic sector allocation strategy based on economic cycle analysis, yield curve dynamics, and commodity price movements. Uses machine learning to identify regime changes and optimal sector exposures.",
    type: "Sector Rotation",
    category: "macro",
    difficulty: 3,
    components: ["Economic Data", "Yield Curve", "Sector ETFs", "Commodity Prices", "Regime Detection"],
    metrics: [
      { label: "Win Rate", value: "71%" },
      { label: "Sharpe", value: "2.0" },
      { label: "Annual Return", value: "29%" },
      { label: "Max Drawdown", value: "-16%" },
    ],
    implementation: [
      { title: "Economic Indicators", desc: "Track leading indicators: yield curve, credit spreads, PMI data" },
      { title: "Sector Scoring", desc: "Rank sectors based on economic cycle positioning" },
      { title: "Regime Classification", desc: "Use HMM to identify early/mid/late cycle phases" },
      { title: "Portfolio Construction", desc: "Equal risk contribution across selected sectors" },
    ],
    risks: "Economic cycle timing is challenging. Sector leadership can change rapidly during transitions.",
  },
  {
    id: "credit-equity-arb",
    title: "Credit-Equity Arbitrage",
    desc: "Exploits pricing discrepancies between a company's equity and credit instruments. Uses structural models to identify mispricing and implements delta-neutral strategies across capital structure.",
    type: "Capital Structure Arbitrage",
    category: "arbitrage",
    difficulty: 4,
    components: ["Credit Spreads", "Equity Prices", "Structural Models", "Options Data", "Fundamental Analysis"],
    metrics: [
      { label: "Win Rate", value: "78%" },
      { label: "Sharpe", value: "2.6" },
      { label: "Annual Return", value: "24%" },
      { label: "Max Drawdown", value: "-11%" },
    ],
    implementation: [
      { title: "Universe Selection", desc: "Focus on liquid names with both equity and CDS/bond markets" },
      { title: "Merton Model Calibration", desc: "Use equity vol and price to imply credit spreads" },
      { title: "Relative Value Analysis", desc: "Compare implied vs actual credit spreads" },
      { title: "Hedged Implementation", desc: "Long undervalued, short overvalued with delta hedging" },
    ],
    risks: "Model risk in structural credit models. Liquidity risk in credit instruments during stress.",
  },
  {
    id: "merger-arbitrage",
    title: "Risk Arbitrage with ML Enhancement",
    desc: "Traditional merger arbitrage enhanced with machine learning models to predict deal completion probability. Incorporates regulatory analysis, antitrust risk assessment, and market sentiment indicators.",
    type: "Event-Driven",
    category: "arbitrage",
    difficulty: 4,
    components: ["M&A Data", "Regulatory Filings", "ML Classification", "Options Analysis", "Legal Research"],
    metrics: [
      { label: "Win Rate", value: "85%" },
      { label: "Sharpe", value: "2.4" },
      { label: "Annual Return", value: "19%" },
      { label: "Max Drawdown", value: "-7%" },
    ],
    implementation: [
      { title: "Deal Screening", desc: "Monitor announced deals, filter by size and regulatory complexity" },
      { title: "Probability Modeling", desc: "ML model using deal terms, regulatory history, market conditions" },
      { title: "Risk Assessment", desc: "Analyze antitrust risk, financing conditions, shareholder approval" },
      { title: "Position Sizing", desc: "Size positions based on deal probability and expected timeline" },
    ],
    risks: "Deal breaks can cause significant losses. Regulatory changes can impact entire strategy.",
  },
  {
    id: "convertible-arbitrage",
    title: "Convertible Bond Arbitrage",
    desc: "Delta-neutral strategy exploiting mispricing in convertible bonds. Uses advanced option pricing models, volatility forecasting, and credit analysis to capture embedded option value while hedging directional risk.",
    type: "Relative Value",
    category: "arbitrage",
    difficulty: 4,
    components: ["Convertible Bonds", "Options Pricing", "Credit Analysis", "Volatility Models", "Greeks Management"],
    metrics: [
      { label: "Win Rate", value: "73%" },
      { label: "Sharpe", value: "2.2" },
      { label: "Annual Return", value: "21%" },
      { label: "Max Drawdown", value: "-13%" },
    ],
    implementation: [
      { title: "Bond Screening", desc: "Identify convertibles with attractive risk-reward profiles" },
      { title: "Fair Value Modeling", desc: "Use binomial trees with credit risk and call provisions" },
      { title: "Delta Hedging", desc: "Maintain delta neutrality through dynamic equity hedging" },
      { title: "Volatility Trading", desc: "Capture gamma profits from volatility vs realized vol" },
    ],
    risks: "Credit deterioration can cause significant losses. Gamma hedging requires frequent rebalancing.",
  },
  {
    id: "commodity-momentum",
    title: "Commodity Trend Following",
    desc: "Multi-timeframe trend following system specifically designed for commodity futures. Incorporates seasonality, storage costs, and supply/demand fundamentals with advanced risk management techniques.",
    type: "Trend Following",
    category: "commodities",
    difficulty: 3,
    components: ["Futures Data", "Seasonality Analysis", "Fundamental Data", "Momentum Indicators", "Risk Parity"],
    metrics: [
      { label: "Win Rate", value: "58%" },
      { label: "Sharpe", value: "1.8" },
      { label: "Annual Return", value: "34%" },
      { label: "Max Drawdown", value: "-19%" },
    ],
    implementation: [
      { title: "Universe Selection", desc: "Trade 20+ liquid commodity futures across energy, metals, agriculture" },
      { title: "Trend Identification", desc: "Multi-timeframe moving average crossovers with momentum confirmation" },
      { title: "Seasonal Adjustment", desc: "Adjust position sizes based on historical seasonal patterns" },
      { title: "Fundamental Overlay", desc: "Incorporate inventory data and supply/demand forecasts" },
    ],
    risks: "Vulnerable to sideways markets and false breakouts. Requires sophisticated risk management.",
  },
  {
    id: "dispersion-trading",
    title: "Index Dispersion Trading",
    desc: "Exploits the volatility difference between index options and individual stock options. Uses correlation forecasting and sector analysis to identify optimal dispersion opportunities across multiple indices.",
    type: "Volatility Trading",
    category: "options",
    difficulty: 4,
    components: ["Index Options", "Single Stock Options", "Correlation Models", "Volatility Forecasting", "Greeks Management"],
    metrics: [
      { label: "Win Rate", value: "67%" },
      { label: "Sharpe", value: "2.3" },
      { label: "Annual Return", value: "27%" },
      { label: "Max Drawdown", value: "-15%" },
    ],
    implementation: [
      { title: "Correlation Analysis", desc: "Monitor realized vs implied correlations across index components" },
      { title: "Dispersion Identification", desc: "Calculate theoretical vs market dispersion premiums" },
      { title: "Structure Implementation", desc: "Long individual vol, short index vol with optimal weightings" },
      { title: "Dynamic Hedging", desc: "Manage delta and vega exposure across all positions" },
    ],
    risks: "Correlation spikes during market stress can cause significant losses. Requires sophisticated hedging.",
  },
  {
    id: "fixed-income-arb",
    title: "Fixed Income Relative Value",
    desc: "Multi-strategy fixed income arbitrage including yield curve trades, swap spreads, and basis trading. Uses principal component analysis and term structure models for risk management and opportunity identification.",
    type: "Fixed Income",
    category: "arbitrage",
    difficulty: 4,
    components: ["Bond Data", "Swap Rates", "Yield Curve Models", "PCA Analysis", "Duration Hedging"],
    metrics: [
      { label: "Win Rate", value: "79%" },
      { label: "Sharpe", value: "2.8" },
      { label: "Annual Return", value: "16%" },
      { label: "Max Drawdown", value: "-6%" },
    ],
    implementation: [
      { title: "Curve Analysis", desc: "Identify rich/cheap bonds using Nelson-Siegel and spline models" },
      { title: "Spread Trading", desc: "Trade credit spreads, swap spreads, and basis relationships" },
      { title: "Risk Management", desc: "Use PCA to hedge interest rate risk across curve" },
      { title: "Carry Optimization", desc: "Maximize carry while maintaining duration neutrality" },
    ],
    risks: "Interest rate volatility and credit events can impact spread relationships. Requires deep fixed income expertise.",
  },
  {
    id: "crypto-funding-arb",
    title: "Cryptocurrency Funding Rate Arbitrage",
    desc: "Exploits funding rate differentials across cryptocurrency perpetual futures exchanges. Includes basis trading, calendar spreads, and cross-exchange arbitrage with automated execution and risk management.",
    type: "Cryptocurrency",
    category: "crypto",
    difficulty: 3,
    components: ["Perpetual Futures", "Funding Rates", "Cross-Exchange Data", "Automated Execution", "Risk Controls"],
    metrics: [
      { label: "Win Rate", value: "88%" },
      { label: "Sharpe", value: "3.4" },
      { label: "APY", value: "156%" },
      { label: "Max Drawdown", value: "-8%" },
    ],
    implementation: [
      { title: "Rate Monitoring", desc: "Track funding rates across Binance, FTX, Bybit, OKX, Deribit" },
      { title: "Arbitrage Identification", desc: "Calculate risk-adjusted returns after fees and slippage" },
      { title: "Automated Execution", desc: "API-based trading with sub-second execution times" },
      { title: "Risk Management", desc: "Position limits, exchange risk controls, and liquidation monitoring" },
    ],
    risks: "Exchange counterparty risk and regulatory uncertainty. Requires robust technical infrastructure.",
  },
  {
    id: "news-sentiment-alpha",
    title: "News Sentiment Alpha Generation",
    desc: "Advanced NLP system processing real-time news, earnings calls, and social media to generate trading signals. Uses transformer models, sentiment analysis, and entity recognition for multi-asset alpha generation.",
    type: "Alternative Data",
    category: "ml",
    difficulty: 4,
    components: ["News Data", "NLP Models", "Sentiment Analysis", "Entity Recognition", "Signal Processing"],
    metrics: [
      { label: "Win Rate", value: "66%" },
      { label: "Sharpe", value: "2.1" },
      { label: "Annual Return", value: "41%" },
      { label: "Max Drawdown", value: "-17%" },
    ],
    implementation: [
      { title: "Data Ingestion", desc: "Real-time feeds from Reuters, Bloomberg, Twitter, Reddit, Discord" },
      { title: "NLP Processing", desc: "BERT-based models for sentiment, entity extraction, and topic modeling" },
      { title: "Signal Generation", desc: "Convert sentiment scores to trading signals with decay functions" },
      { title: "Portfolio Construction", desc: "Risk-adjusted position sizing with sector and market cap constraints" },
    ],
    risks: "Model degradation over time and false signals from market manipulation. Requires continuous retraining.",
  },
  {
    id: "options-flow-following",
    title: "Institutional Options Flow Following",
    desc: "Identifies and follows large institutional options trades using advanced flow detection algorithms. Combines unusual options activity with technical analysis and earnings calendars for directional alpha.",
    type: "Options Flow",
    category: "options",
    difficulty: 3,
    components: ["Options Data", "Flow Detection", "Technical Analysis", "Earnings Calendar", "Risk Management"],
    metrics: [
      { label: "Win Rate", value: "72%" },
      { label: "Sharpe", value: "2.0" },
      { label: "Annual Return", value: "36%" },
      { label: "Max Drawdown", value: "-18%" },
    ],
    implementation: [
      { title: "Flow Detection", desc: "Identify unusual options volume and open interest changes" },
      { title: "Trade Classification", desc: "Distinguish between hedging and speculative flows" },
      { title: "Signal Confirmation", desc: "Combine with technical levels and earnings proximity" },
      { title: "Execution Strategy", desc: "Follow institutional flows with appropriate position sizing" },
    ],
    risks: "Institutional flows may be hedging rather than directional. Requires sophisticated flow analysis.",
  },
  {
    id: "gamma-scalping",
    title: "Delta-Neutral Gamma Scalping",
    desc: "Market-neutral strategy that profits from realized volatility being higher than implied volatility. Uses dynamic delta hedging of long options positions to capture gamma profits from intraday price movements.",
    type: "Market Neutral",
    category: "options",
    difficulty: 4,
    components: ["Options Chain", "Real-time Pricing", "Greeks Calculation", "Delta Hedging", "Volatility Analysis"],
    metrics: [
      { label: "Win Rate", value: "69%" },
      { label: "Sharpe", value: "2.4" },
      { label: "Annual Return", value: "23%" },
      { label: "Max Drawdown", value: "-12%" },
    ],
    implementation: [
      { title: "Option Selection", desc: "Buy ATM options with high implied vol vs realized vol" },
      { title: "Delta Hedging", desc: "Continuously hedge delta exposure through stock trading" },
      { title: "Gamma Capture", desc: "Profit from gamma as stock moves throughout the day" },
      { title: "Theta Management", desc: "Monitor time decay and adjust positions accordingly" },
    ],
    risks: "Low volatility periods reduce profitability. Requires frequent rebalancing and tight risk controls.",
  },
  {
    id: "cross-asset-momentum",
    title: "Cross-Asset Momentum Strategy",
    desc: "Global momentum strategy across equities, bonds, commodities, and currencies. Uses risk parity allocation and regime-dependent parameters to adapt to different market environments and correlation structures.",
    type: "Multi-Asset",
    category: "momentum",
    difficulty: 4,
    components: ["Multi-Asset Data", "Risk Parity", "Momentum Indicators", "Regime Detection", "Correlation Analysis"],
    metrics: [
      { label: "Win Rate", value: "63%" },
      { label: "Sharpe", value: "1.9" },
      { label: "Annual Return", value: "28%" },
      { label: "Max Drawdown", value: "-16%" },
    ],
    implementation: [
      { title: "Universe Construction", desc: "Select liquid instruments across 4 major asset classes" },
      { title: "Momentum Scoring", desc: "Combine 1, 3, 6, and 12-month momentum with volatility adjustment" },
      { title: "Risk Allocation", desc: "Equal risk contribution across asset classes and instruments" },
      { title: "Regime Adaptation", desc: "Adjust lookback periods based on market volatility regime" },
    ],
    risks: "Momentum crashes during market reversals. Requires sophisticated risk management across asset classes.",
  },
  {
    id: "volatility-surface-arb",
    title: "Volatility Surface Arbitrage",
    desc: "Exploits mispricing across the volatility surface by trading options with different strikes and expirations. Uses advanced volatility models and surface fitting techniques to identify relative value opportunities.",
    type: "Volatility Trading",
    category: "options",
    difficulty: 5,
    components: ["Options Chain", "Volatility Surface", "SVI Models", "Greeks Management", "Model Calibration"],
    metrics: [
      { label: "Win Rate", value: "75%" },
      { label: "Sharpe", value: "2.7" },
      { label: "Annual Return", value: "32%" },
      { label: "Max Drawdown", value: "-14%" },
    ],
    implementation: [
      { title: "Surface Modeling", desc: "Fit SVI or SABR models to implied volatility surface" },
      { title: "Arbitrage Detection", desc: "Identify options trading away from model fair value" },
      { title: "Strategy Implementation", desc: "Long cheap options, short expensive options" },
      { title: "Risk Management", desc: "Hedge delta, gamma, vega, and theta exposures" },
    ],
    risks: "Model risk and volatility regime changes can impact surface relationships. Requires sophisticated modeling.",
  },
  {
    id: "intraday-reversal",
    title: "Intraday Mean Reversion",
    desc: "High-frequency mean reversion strategy exploiting intraday price reversals in liquid stocks. Uses microstructure analysis, order flow imbalance, and statistical models to identify temporary price dislocations.",
    type: "Intraday",
    category: "mean-reversion",
    difficulty: 4,
    components: ["Tick Data", "Order Flow", "Microstructure Models", "Statistical Tests", "Execution Algorithms"],
    metrics: [
      { label: "Win Rate", value: "81%" },
      { label: "Sharpe", value: "3.2" },
      { label: "Daily Return", value: "0.15%" },
      { label: "Max Drawdown", value: "-4%" },
    ],
    implementation: [
      { title: "Signal Generation", desc: "Identify mean reversion opportunities using z-score analysis" },
      { title: "Order Flow Analysis", desc: "Monitor bid-ask imbalances and volume patterns" },
      { title: "Entry Timing", desc: "Use microstructure signals for optimal entry points" },
      { title: "Risk Controls", desc: "Tight stop losses and position limits for capital preservation" },
    ],
    risks: "Vulnerable to trending moves and requires sophisticated execution. High transaction costs can erode profits.",
  },
  {
    id: "calendar-spread-trading",
    title: "Systematic Calendar Spread Trading",
    desc: "Exploits time decay and volatility differences between near and far-dated options. Uses volatility forecasting and term structure analysis to identify optimal calendar spread opportunities across multiple underlyings.",
    type: "Options Strategies",
    category: "options",
    difficulty: 3,
    components: ["Options Chain", "Volatility Term Structure", "Time Decay Analysis", "Volatility Forecasting", "Greeks Management"],
    metrics: [
      { label: "Win Rate", value: "77%" },
      { label: "Sharpe", value: "2.1" },
      { label: "Annual Return", value: "25%" },
      { label: "Max Drawdown", value: "-11%" },
    ],
    implementation: [
      { title: "Spread Selection", desc: "Identify underlyings with favorable volatility term structure" },
      { title: "Structure Optimization", desc: "Choose optimal strikes and expirations for maximum theta capture" },
      { title: "Volatility Analysis", desc: "Monitor implied vs realized volatility relationships" },
      { title: "Position Management", desc: "Adjust or close positions based on P&L and Greeks exposure" },
    ],
    risks: "Large price movements can cause losses. Requires active management and volatility expertise.",
  }
]
