/**
 * 🚀 TRADING STRATEGY DEFINITIONS
 * Shared types between NexQuantSite and NexuralTrading Universe
 */

/**
 * Signal types that can be generated by trading strategies
 */
export enum SignalType {
  LONG = 'LONG',
  SHORT = 'SHORT',
  EXIT = 'EXIT',
  NEUTRAL = 'NEUTRAL',
}

/**
 * Trading signal generated by a strategy
 */
export interface TradingSignal {
  id?: string;
  strategyId: string;
  instrumentId: string;
  timestamp: number;
  type: SignalType;
  confidence: number;
  price?: number;
  targetPrice?: number;
  stopPrice?: number;
  metadata: Record<string, any>;
  createdAt?: Date;
}

/**
 * Parameter for a trading strategy
 */
export interface StrategyParameter {
  id: string;
  name: string;
  description: string;
  type: 'number' | 'boolean' | 'string' | 'enum';
  defaultValue: any;
  range?: [number, number]; // For numeric parameters
  options?: string[]; // For enum parameters
  isRequired: boolean;
  isAdvanced: boolean;
}

/**
 * Distribution channel for a strategy
 */
export enum DistributionChannel {
  DISCORD = 'DISCORD',
  DESKTOP_APP = 'DESKTOP_APP',
  MOBILE_APP = 'MOBILE_APP',
  EMAIL = 'EMAIL',
}

/**
 * Definition of a trading strategy
 */
export interface StrategyDefinition {
  id: string;
  name: string;
  description: string;
  version: string;
  parameters: StrategyParameter[];
  tags: string[];
  supportedInstruments: string[];
  distributionChannels: DistributionChannel[];
  subscriptionTiers: string[]; // Which subscription tiers have access
  isActive: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

/**
 * Strategy instance with specific parameter values
 */
export interface StrategyInstance {
  id: string;
  strategyDefinitionId: string;
  name: string;
  parameters: Record<string, any>;
  isActive: boolean;
  userId: string;
  createdAt?: Date;
  updatedAt?: Date;
}

/**
 * Strategy performance metrics
 */
export interface StrategyPerformance {
  strategyId: string;
  period: 'day' | 'week' | 'month' | 'year' | 'all';
  winRate: number;
  totalSignals: number;
  profitFactor: number;
  averageReturn: number;
  maxDrawdown: number;
  sharpeRatio: number;
  metadata: Record<string, any>;
  updatedAt: Date;
}
